"""init

Revision ID: f4ae4e825aed
Revises: 
Create Date: 2026-01-26 17:20:18.595703

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sparket.validator.database.schema.base import market_kind_enum, market_result_enum, price_side_enum, score_component_enum, task_type_enum
from sqlalchemy.dialects import postgresql

_ENUM_NAMES = (
    "market_kind_enum",
    "market_result_enum",
    "price_side_enum",
    "score_component_enum",
    "task_type_enum",
)
_ENUMS = [globals().get(name) for name in _ENUM_NAMES]


def _create_enums(bind) -> None:
    for enum in (e for e in _ENUMS if e is not None):
        try:
            enum.create(bind, checkfirst=True)
        except AttributeError:
            continue


def _drop_enums(bind) -> None:
    for enum in (e for e in reversed(_ENUMS) if e is not None):
        try:
            enum.drop(bind, checkfirst=True)
        except AttributeError:
            continue


# revision identifiers, used by Alembic.
revision = 'f4ae4e825aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    _create_enums(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal surrogate primary key'),
    sa.Column('topic', sa.String(), nullable=False, comment='Inbound topic or acknowledgment type'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Inbound message payload awaiting processing'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when the message was received'),
    sa.Column('processed', sa.Boolean(), nullable=False, comment='Indicates whether the message has been handled'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the message was processed (UTC)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of processing attempts'),
    sa.Column('last_error', sa.String(), nullable=True, comment='Most recent processing error (if any)'),
    sa.Column('dedupe_key', sa.String(), nullable=True, comment='Idempotency key for inbound messages'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox')),
    comment='Inbox table for idempotent processing of acknowledgements and callbacks'
    )
    op.create_index('ix_inbox_created_at', 'inbox', ['created_at'], unique=False)
    op.create_index('ix_inbox_processed', 'inbox', ['processed'], unique=False)
    op.create_index('ix_inbox_processed_at', 'inbox', ['processed_at'], unique=False)
    op.create_index('ix_inbox_topic', 'inbox', ['topic'], unique=False)
    op.create_table('miner',
    sa.Column('miner_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Internal surrogate key for miner records'),
    sa.Column('hotkey', sa.String(), nullable=False, comment='Hotkey identifier (matches Bittensor neuron hotkey)'),
    sa.Column('coldkey', sa.String(), nullable=False, comment='Coldkey address associated with the miner'),
    sa.Column('uid', sa.Integer(), nullable=False, comment='Neuron UID on the Bittensor subnet'),
    sa.Column('netuid', sa.Integer(), nullable=False, comment='Subnet network identifier'),
    sa.Column('active', sa.Integer(), nullable=False, comment='Active flag from metagraph (1 if participating)'),
    sa.Column('stake', sa.Numeric(), nullable=False, comment='Current stake balance for the hotkey'),
    sa.Column('stake_dict', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Breakdown of stake by delegator coldkey'),
    sa.Column('total_stake', sa.Numeric(), nullable=False, comment='Synced copy of total stake (for quick filtering)'),
    sa.Column('rank', sa.Numeric(), nullable=False, comment='Current rank metric'),
    sa.Column('emission', sa.Numeric(), nullable=False, comment='Emission rate'),
    sa.Column('incentive', sa.Numeric(), nullable=False, comment='Incentive score'),
    sa.Column('consensus', sa.Numeric(), nullable=False, comment='Consensus score'),
    sa.Column('trust', sa.Numeric(), nullable=False, comment='Trust value from metagraph'),
    sa.Column('validator_trust', sa.Numeric(), nullable=False, comment='Validator trust component'),
    sa.Column('dividends', sa.Numeric(), nullable=False, comment='Dividends metric'),
    sa.Column('last_update', sa.Integer(), nullable=False, comment='Block height of last metagraph update'),
    sa.Column('validator_permit', sa.Boolean(), nullable=False, comment='Whether the miner currently has validator permit'),
    sa.Column('prometheus_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Optional Prometheus endpoint metadata'),
    sa.Column('axon_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Axon configuration snapshot (NeuronInfoLite.axon_info)'),
    sa.Column('pruning_score', sa.Integer(), nullable=False, comment='Score used for pruning decisions'),
    sa.Column('is_null', sa.Boolean(), nullable=False, comment='Marker for placeholder/null neuron entries'),
    sa.PrimaryKeyConstraint('miner_id', name=op.f('pk_miner')),
    sa.UniqueConstraint('hotkey', name=op.f('uq_miner_hotkey')),
    sa.UniqueConstraint('miner_id', 'hotkey', name='uq_miner_id_hotkey')
    )
    op.create_index('ix_miner_netuid_uid', 'miner', ['netuid', 'uid'], unique=True)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal surrogate primary key'),
    sa.Column('topic', sa.String(), nullable=False, comment='Message topic consumed by downstream delivery'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Exactly-once payload awaiting transport'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC enqueue timestamp'),
    sa.Column('sent', sa.Boolean(), nullable=False, comment='Delivery flag set by transport'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    comment='Outbox pattern table ensuring exactly-once publication'
    )
    op.create_index('ix_outbox_created_at', 'outbox', ['created_at'], unique=False)
    op.create_index('ix_outbox_sent', 'outbox', ['sent'], unique=False)
    op.create_index('ix_outbox_topic', 'outbox', ['topic'], unique=False)
    op.create_table('provider',
    sa.Column('provider_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identifier for an odds provider or book'),
    sa.Column('code', sa.String(), nullable=False, comment="Short provider code (e.g. 'PINN')"),
    sa.Column('name', sa.String(), nullable=False, comment='Human-friendly provider name'),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('pk_provider')),
    sa.UniqueConstraint('code', name=op.f('uq_provider_code'))
    )
    op.create_table('scoring_job_state',
    sa.Column('job_id', sa.String(length=64), nullable=False, comment="Unique job identifier (e.g., 'rolling_aggregates_v1')"),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Job status: pending, running, completed, failed'),
    sa.Column('last_checkpoint', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last checkpoint (UTC)'),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Job-specific checkpoint state for resume'),
    sa.Column('items_total', sa.Integer(), nullable=True, comment='Total items to process (if known)'),
    sa.Column('items_processed', sa.Integer(), nullable=False, comment='Number of items processed so far'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When the job started (UTC)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the job completed (UTC)'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Scheduled next execution time (UTC)'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='Consecutive error count for backoff'),
    sa.Column('last_error', sa.String(), nullable=True, comment='Most recent error message'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_scoring_job_state'))
    )
    op.create_index('ix_scoring_job_state_next_run', 'scoring_job_state', ['next_run_at'], unique=False)
    op.create_index('ix_scoring_job_state_status', 'scoring_job_state', ['status'], unique=False)
    op.create_table('scoring_work_queue',
    sa.Column('work_id', sa.String(length=64), nullable=False, comment='Unique work item identifier (UUID)'),
    sa.Column('work_type', sa.String(length=32), nullable=False, comment='Type of work: snapshot, outcome, rolling, skill'),
    sa.Column('chunk_key', sa.String(length=128), nullable=False, comment='Chunk identifier (e.g., miner range, market batch)'),
    sa.Column('params', sa.String(), nullable=True, comment='JSON-encoded parameters for this work item'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority = processed first'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Status: pending, claimed, completed, failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this work item was created (UTC)'),
    sa.Column('claimed_by', sa.String(length=64), nullable=True, comment='Worker ID that claimed this work'),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True, comment='When this work was claimed (UTC)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When this work was completed (UTC)'),
    sa.Column('result', sa.String(), nullable=True, comment='JSON-encoded result data'),
    sa.Column('error', sa.String(length=1000), nullable=True, comment='Error message if failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.PrimaryKeyConstraint('work_id', name=op.f('pk_scoring_work_queue'))
    )
    op.create_index('ix_scoring_work_queue_claimed', 'scoring_work_queue', ['claimed_at'], unique=False)
    op.create_index('ix_scoring_work_queue_priority', 'scoring_work_queue', ['priority', 'created_at'], unique=False)
    op.create_index('ix_scoring_work_queue_status', 'scoring_work_queue', ['status'], unique=False)
    op.create_index('ix_scoring_work_queue_type_status', 'scoring_work_queue', ['work_type', 'status'], unique=False)
    op.create_index('uq_scoring_work_queue_type_chunk', 'scoring_work_queue', ['work_type', 'chunk_key'], unique=True)
    op.create_table('scoring_worker_heartbeat',
    sa.Column('worker_id', sa.String(length=64), nullable=False, comment='Unique worker identifier'),
    sa.Column('pid', sa.Integer(), nullable=False, comment='OS process ID'),
    sa.Column('hostname', sa.String(length=128), nullable=False, comment='Machine hostname'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When the worker started (UTC)'),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False, comment='Most recent heartbeat timestamp (UTC)'),
    sa.Column('current_job', sa.String(length=64), nullable=True, comment='Currently executing job ID (if any)'),
    sa.Column('jobs_completed', sa.Integer(), nullable=False, comment='Total jobs completed by this worker'),
    sa.Column('jobs_failed', sa.Integer(), nullable=False, comment='Total jobs failed by this worker'),
    sa.Column('memory_mb', sa.Integer(), nullable=True, comment='Current memory usage in MB'),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_scoring_worker_heartbeat'))
    )
    op.create_index('ix_scoring_worker_heartbeat_last', 'scoring_worker_heartbeat', ['last_heartbeat'], unique=False)
    op.create_table('sport',
    sa.Column('sport_id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal identifier for a sport grouping'),
    sa.Column('code', sa.String(), nullable=False, comment="Stable code (e.g. 'nba', 'mlb') used throughout the system"),
    sa.Column('name', sa.String(), nullable=False, comment='Human-friendly sport name'),
    sa.PrimaryKeyConstraint('sport_id', name=op.f('pk_sport')),
    sa.UniqueConstraint('code', name=op.f('uq_sport_code'))
    )
    op.create_table('league',
    sa.Column('league_id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal identifier for a league or competition'),
    sa.Column('sport_id', sa.Integer(), nullable=False, comment='Parent sport (fk to sport)'),
    sa.Column('code', sa.String(), nullable=False, comment="League code (e.g. 'EPL', 'NBA')"),
    sa.Column('name', sa.String(), nullable=False, comment='League display name'),
    sa.Column('ext_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='External provider identifiers keyed by origin'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.sport_id'], name=op.f('fk_league_sport_id_sport'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_league')),
    sa.UniqueConstraint('sport_id', 'code', name='uq_league_sport_code')
    )
    op.create_table('miner_rolling_score',
    sa.Column('miner_id', sa.BigInteger(), nullable=False, comment='Miner identifier'),
    sa.Column('miner_hotkey', sa.String(), nullable=False, comment='Miner hotkey at the time of aggregation'),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False, comment='Timestamp the rolling view represents (UTC)'),
    sa.Column('window_days', sa.Integer(), nullable=False, comment='Number of days in the rolling window'),
    sa.Column('n_submissions', sa.Integer(), nullable=False, comment='Number of submissions contributing to the window'),
    sa.Column('n_eff', sa.Numeric(), nullable=True, comment='Effective sample size after exponential decay weighting'),
    sa.Column('es_mean', sa.Numeric(), nullable=True, comment='Average closed-line efficiency (CLE)'),
    sa.Column('es_std', sa.Numeric(), nullable=True, comment='Std dev of CLE for risk adjustment'),
    sa.Column('es_adj', sa.Numeric(), nullable=True, comment='Risk-adjusted edge (es_mean / es_std)'),
    sa.Column('mes_mean', sa.Numeric(), nullable=True, comment='Average market efficiency score'),
    sa.Column('sos_mean', sa.Numeric(), nullable=True, comment='Average originality score (1 - |corr|)'),
    sa.Column('pss_mean', sa.Numeric(), nullable=True, comment='Average predictive skill score (time-adjusted)'),
    sa.Column('fq_raw', sa.Numeric(), nullable=True, comment='Forecast quality raw score'),
    sa.Column('brier_mean', sa.Numeric(), nullable=True, comment='Average Brier score vs outcome (raw accuracy)'),
    sa.Column('lead_ratio', sa.Numeric(), nullable=True, comment='Fraction of moves where miner led market'),
    sa.Column('fq_score', sa.Numeric(), nullable=True, comment='Forecast quality normalized [0,1]'),
    sa.Column('cal_score', sa.Numeric(), nullable=True, comment='Calibration score [0,1]'),
    sa.Column('sharp_score', sa.Numeric(), nullable=True, comment='Sharpness score [0,1]'),
    sa.Column('edge_score', sa.Numeric(), nullable=True, comment='Economic edge normalized [0,1]'),
    sa.Column('mes_score', sa.Numeric(), nullable=True, comment='Market efficiency normalized [0,1]'),
    sa.Column('sos_score', sa.Numeric(), nullable=True, comment='Originality score normalized [0,1]'),
    sa.Column('lead_score', sa.Numeric(), nullable=True, comment='Lead ratio normalized [0,1]'),
    sa.Column('forecast_dim', sa.Numeric(), nullable=True, comment='Forecast dimension = 0.6*FQ + 0.4*CAL'),
    sa.Column('econ_dim', sa.Numeric(), nullable=True, comment='Economic dimension = 0.7*EDGE + 0.3*MES'),
    sa.Column('info_dim', sa.Numeric(), nullable=True, comment='Info dimension = 0.6*SOS + 0.4*LEAD'),
    sa.Column('skill_score', sa.Numeric(), nullable=True, comment='Final skill score = 0.5*Forecast + 0.3*Econ + 0.2*Info'),
    sa.Column('composite_score', sa.Numeric(), nullable=True, comment='Legacy composite (deprecated, use skill_score)'),
    sa.Column('score_version', sa.Integer(), nullable=False, comment='Version number for cross-validator consensus'),
    sa.ForeignKeyConstraint(['miner_id', 'miner_hotkey'], ['miner.miner_id', 'miner.hotkey'], name='fk_miner_rolling_score_miner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('miner_id', 'miner_hotkey', 'as_of', 'window_days', name=op.f('pk_miner_rolling_score'))
    )
    op.create_index('ix_miner_rolling_score_as_of', 'miner_rolling_score', ['as_of'], unique=False)
    op.create_index('ix_miner_rolling_score_skill', 'miner_rolling_score', ['skill_score'], unique=False)
    op.create_table('sportsbook',
    sa.Column('sportsbook_id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal identifier for the sportsbook'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='Parent provider (e.g., SportsDataIO)'),
    sa.Column('code', sa.String(length=32), nullable=False, comment="Unique sportsbook code (e.g., 'PINN', 'DKNG')"),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Human-readable sportsbook name'),
    sa.Column('is_sharp', sa.Boolean(), nullable=False, comment='Whether this is a known sharp book (e.g., Pinnacle)'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Whether to include in consensus calculations'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], name=op.f('fk_sportsbook_provider_id_provider'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sportsbook_id', name=op.f('pk_sportsbook')),
    sa.UniqueConstraint('code', name=op.f('uq_sportsbook_code'))
    )
    op.create_index('ix_sportsbook_active', 'sportsbook', ['active'], unique=False)
    op.create_index('ix_sportsbook_provider', 'sportsbook', ['provider_id'], unique=False)
    op.create_table('sportsbook_bias',
    sa.Column('sportsbook_id', sa.Integer(), nullable=False, comment='Sportsbook being calibrated'),
    sa.Column('sport_id', sa.Integer(), nullable=False, comment='Sport context for bias estimation'),
    sa.Column('market_kind', market_kind_enum, nullable=False, comment='Market type (moneyline, spread, total)'),
    sa.Column('bias_factor', sa.Numeric(precision=10, scale=6), nullable=False, comment='Multiplicative bias factor (1.0 = no bias)'),
    sa.Column('variance', sa.Numeric(precision=10, scale=6), nullable=False, comment="Estimated variance of book's errors for inverse-variance weighting"),
    sa.Column('sample_count', sa.Integer(), nullable=False, comment='Number of settled outcomes used in estimation'),
    sa.Column('mean_squared_error', sa.Numeric(precision=12, scale=8), nullable=True, comment='MSE of book vs realized outcomes'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for consensus (increments on update)'),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, comment='When this bias estimate was computed (UTC)'),
    sa.Column('input_hash', sa.String(length=64), nullable=True, comment='SHA256 hash of inputs for determinism verification'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.sport_id'], name=op.f('fk_sportsbook_bias_sport_id_sport'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbook.sportsbook_id'], name=op.f('fk_sportsbook_bias_sportsbook_id_sportsbook'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sportsbook_id', 'sport_id', 'market_kind', name=op.f('pk_sportsbook_bias'))
    )
    op.create_index('ix_sportsbook_bias_computed', 'sportsbook_bias', ['computed_at'], unique=False)
    op.create_index('ix_sportsbook_bias_version', 'sportsbook_bias', ['version'], unique=False)
    op.create_table('team',
    sa.Column('team_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Global identifier for a team or competitor'),
    sa.Column('league_id', sa.Integer(), nullable=False, comment='League that the team belongs to'),
    sa.Column('name', sa.String(), nullable=False, comment='Team name'),
    sa.Column('abbrev', sa.String(), nullable=True, comment='Short code or abbreviation, if applicable'),
    sa.Column('ext_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='External provider identifiers keyed by origin'),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], name=op.f('fk_team_league_id_league'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_team'))
    )
    op.create_table('event',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identifier for a scheduled sporting event'),
    sa.Column('league_id', sa.Integer(), nullable=False, comment='League the event belongs to'),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True, comment='Home team reference'),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True, comment='Away team reference'),
    sa.Column('venue', sa.String(), nullable=True, comment='Venue or location'),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False, comment='Scheduled start time in UTC'),
    sa.Column('status', sa.String(), nullable=False, comment='Lifecycle state (scheduled/in_play/finished/void)'),
    sa.Column('ext_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Provider event identifiers or metadata'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Row creation timestamp (UTC)'),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.team_id'], name=op.f('fk_event_away_team_id_team')),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.team_id'], name=op.f('fk_event_home_team_id_team')),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], name=op.f('fk_event_league_id_league')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event'))
    )
    op.create_index('ix_event_league_start', 'event', ['league_id', 'start_time_utc'], unique=False)
    op.create_index('ix_event_status_start', 'event', ['status', 'start_time_utc'], unique=False)
    op.create_table('market',
    sa.Column('market_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Identifier for a bettable market on an event'),
    sa.Column('event_id', sa.BigInteger(), nullable=False, comment='Parent event'),
    sa.Column('kind', market_kind_enum, nullable=False, comment='Market family (moneyline/spread/total/etc.)'),
    sa.Column('line', sa.Numeric(), nullable=True, comment='Line or total if applicable (NULL for moneyline)'),
    sa.Column('points_team_id', sa.BigInteger(), nullable=True, comment='Team the handicap applies to (for spreads)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the market row was created (UTC)'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_market_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['points_team_id'], ['team.team_id'], name=op.f('fk_market_points_team_id_team')),
    sa.PrimaryKeyConstraint('market_id', name=op.f('pk_market'))
    )
    op.create_index('ix_market_event_kind', 'market', ['event_id', 'kind'], unique=False)
    op.create_index('uq_market_event_kind_line_team', 'market', ['event_id', 'kind', sa.literal_column('coalesce(line, 0)'), sa.literal_column('coalesce(points_team_id, 0)')], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Internal surrogate primary key'),
    sa.Column('event_id', sa.BigInteger(), nullable=False, comment='FK to event.event_id for the scored event'),
    sa.Column('miner_hotkey', sa.String(), nullable=False, comment='Miner being scored'),
    sa.Column('task_type', task_type_enum, nullable=False, comment='Task classification (odds or outcome)'),
    sa.Column('pq', sa.Float(), nullable=True, comment='Price quality component'),
    sa.Column('clv', sa.Float(), nullable=True, comment='Closing line value component'),
    sa.Column('calib', sa.Float(), nullable=True, comment='Calibration component'),
    sa.Column('score_event', sa.Float(), nullable=True, comment='Aggregated per-event score'),
    sa.Column('component', score_component_enum, nullable=False, comment='Lifecycle component (interim/close/final)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this score row was created'),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_scores_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    comment='Per-event scoring breakdowns for miners'
    )
    op.create_index('ix_scores_component', 'scores', ['component'], unique=False)
    op.create_index('ix_scores_created_at', 'scores', ['created_at'], unique=False)
    op.create_index('ix_scores_event_id', 'scores', ['event_id'], unique=False)
    op.create_index('ix_scores_miner_hotkey', 'scores', ['miner_hotkey'], unique=False)
    op.create_index('ix_scores_score_event', 'scores', ['score_event'], unique=False)
    op.create_index('ix_scores_task_type', 'scores', ['task_type'], unique=False)
    op.create_table('ground_truth_closing',
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market this consensus applies to'),
    sa.Column('side', price_side_enum, nullable=False, comment='Outcome side (home, away, over, under, etc.)'),
    sa.Column('prob_consensus', sa.Numeric(precision=10, scale=8), nullable=False, comment='Consensus probability from bias-weighted average'),
    sa.Column('odds_consensus', sa.Numeric(precision=10, scale=4), nullable=False, comment='Consensus decimal odds (1 / prob_consensus)'),
    sa.Column('contributing_books', sa.Integer(), nullable=False, comment='Number of sportsbooks contributing to this consensus'),
    sa.Column('min_prob', sa.Numeric(precision=10, scale=8), nullable=True, comment='Minimum probability across contributing books'),
    sa.Column('max_prob', sa.Numeric(precision=10, scale=8), nullable=True, comment='Maximum probability across contributing books'),
    sa.Column('std_dev', sa.Numeric(precision=10, scale=8), nullable=True, comment='Standard deviation of book probabilities'),
    sa.Column('bias_version', sa.Integer(), nullable=False, comment='Version of sportsbook_bias used for this consensus'),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, comment='When this consensus was computed (UTC)'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_ground_truth_closing_market_id_market'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'side', name=op.f('pk_ground_truth_closing'))
    )
    op.create_index('ix_ground_truth_closing_bias_version', 'ground_truth_closing', ['bias_version'], unique=False)
    op.create_index('ix_ground_truth_closing_computed', 'ground_truth_closing', ['computed_at'], unique=False)
    op.create_table('ground_truth_snapshot',
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market this snapshot applies to'),
    sa.Column('side', price_side_enum, nullable=False, comment='Outcome side (home, away, over, under, etc.)'),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False, comment='When this snapshot was captured (UTC)'),
    sa.Column('prob_consensus', sa.Numeric(precision=10, scale=8), nullable=False, comment='Consensus probability from bias-weighted average'),
    sa.Column('odds_consensus', sa.Numeric(precision=10, scale=4), nullable=False, comment='Consensus decimal odds (1 / prob_consensus)'),
    sa.Column('contributing_books', sa.Integer(), nullable=False, comment='Number of sportsbooks contributing to this consensus'),
    sa.Column('std_dev', sa.Numeric(precision=10, scale=8), nullable=True, comment='Standard deviation of book probabilities'),
    sa.Column('bias_version', sa.Integer(), nullable=False, comment='Version of sportsbook_bias used for this consensus'),
    sa.Column('is_closing', sa.Boolean(), nullable=False, comment='True if this is the final closing line snapshot'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_ground_truth_snapshot_market_id_market'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'side', 'snapshot_ts', name=op.f('pk_ground_truth_snapshot'))
    )
    op.create_index('ix_gt_snapshot_closing', 'ground_truth_snapshot', ['market_id', 'side', 'is_closing'], unique=False)
    op.create_index('ix_gt_snapshot_market_ts', 'ground_truth_snapshot', ['market_id', 'snapshot_ts'], unique=False)
    op.create_table('miner_market_stats',
    sa.Column('miner_id', sa.BigInteger(), nullable=False, comment='Miner being evaluated'),
    sa.Column('miner_hotkey', sa.String(), nullable=False, comment='Miner hotkey at the time of observation'),
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market context'),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False, comment='Beginning of the observation window (UTC)'),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False, comment='End of the observation window (UTC)'),
    sa.Column('corr_raw', sa.Numeric(), nullable=True, comment='Correlation between miner implied probabilities and provider'),
    sa.Column('corr_norm', sa.Numeric(), nullable=True, comment='Correlation using normalized probabilities'),
    sa.Column('lead_seconds', sa.Integer(), nullable=True, comment='Average seconds by which miner leads provider moves'),
    sa.Column('moves_followed_ratio', sa.Numeric(), nullable=True, comment='Fraction of provider moves the miner followed within the window'),
    sa.Column('moves_led_ratio', sa.Numeric(), nullable=True, comment='Fraction of moves the miner led'),
    sa.Column('n_obs', sa.Integer(), nullable=False, comment='Number of quote observations considered'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_miner_market_stats_market_id_market'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['miner_id', 'miner_hotkey'], ['miner.miner_id', 'miner.hotkey'], name='fk_miner_market_stats_miner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('miner_id', 'miner_hotkey', 'market_id', 'window_start', 'window_end', name=op.f('pk_miner_market_stats'))
    )
    op.create_index('ix_miner_market_stats_window_end', 'miner_market_stats', ['window_end'], unique=False)
    op.create_table('miner_submission',
    sa.Column('submission_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for each miner-submitted odds snapshot'),
    sa.Column('miner_id', sa.BigInteger(), nullable=False, comment='Submitting miner (reference to reference.miner)'),
    sa.Column('miner_hotkey', sa.String(), nullable=False, comment='Miner hotkey to disambiguate lifecycle with same uid'),
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market the submission applies to'),
    sa.Column('side', price_side_enum, nullable=False, comment='Which outcome within the market this odds entry refers to'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the validator received the submission (UTC)'),
    sa.Column('priced_at', sa.DateTime(timezone=True), nullable=True, comment='Optional: miner-declared timestamp when they priced the market (UTC)'),
    sa.Column('odds_eu', sa.Numeric(), nullable=False, comment='Miner-supplied decimal odds'),
    sa.Column('imp_prob', sa.Numeric(), nullable=False, comment='Instant implied probability (1/odds_eu)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Opaque metadata from the miner (model version, features, etc.)'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_miner_submission_market_id_market'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['miner_id', 'miner_hotkey'], ['miner.miner_id', 'miner.hotkey'], name='fk_miner_submission_miner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_miner_submission'))
    )
    op.create_index('ix_miner_submission_market_ts', 'miner_submission', ['market_id', 'submitted_at'], unique=False)
    op.create_index('ix_miner_submission_miner_ts', 'miner_submission', ['miner_id', 'miner_hotkey', 'submitted_at'], unique=False)
    op.create_index('uq_miner_submission', 'miner_submission', ['miner_id', 'miner_hotkey', 'market_id', 'side', 'submitted_at'], unique=True)
    op.create_table('outcome',
    sa.Column('outcome_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Primary key for the market outcome record'),
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market this outcome resolves'),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True, comment='When the market was settled (if known, UTC)'),
    sa.Column('result', market_result_enum, nullable=True, comment='Final result (home/away/draw/over/under/etc.)'),
    sa.Column('score_home', sa.Numeric(), nullable=True, comment='Home team final score snapshot'),
    sa.Column('score_away', sa.Numeric(), nullable=True, comment='Away team final score snapshot'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional settlement data or evidence'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_outcome_market_id_market'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('outcome_id', name=op.f('pk_outcome')),
    sa.UniqueConstraint('market_id', name='uq_outcome_market')
    )
    op.create_table('provider_closing',
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='Provider identifier'),
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market identifier'),
    sa.Column('side', price_side_enum, nullable=False, comment='Outcome side'),
    sa.Column('ts_close', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of the closing quote used for scoring (UTC)'),
    sa.Column('odds_eu_close', sa.Numeric(), nullable=False, comment='Closing decimal odds'),
    sa.Column('imp_prob_close', sa.Numeric(), nullable=False, comment='Closing implied probability (raw)'),
    sa.Column('imp_prob_norm_close', sa.Numeric(), nullable=True, comment='Closing implied probability after normalization'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_provider_closing_market_id_market'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], name=op.f('fk_provider_closing_provider_id_provider')),
    sa.PrimaryKeyConstraint('provider_id', 'market_id', 'side', name=op.f('pk_provider_closing'))
    )
    op.create_table('provider_quote',
    sa.Column('quote_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique identifier for each captured provider price tick'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='Source provider for the quote'),
    sa.Column('market_id', sa.BigInteger(), nullable=False, comment='Market the quote applies to'),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the quote was observed (UTC)'),
    sa.Column('side', price_side_enum, nullable=False, comment='Outcome side within the market'),
    sa.Column('odds_eu', sa.Numeric(), nullable=False, comment='Decimal odds from the provider'),
    sa.Column('imp_prob', sa.Numeric(), nullable=False, comment='Implied probability (1/odds) at observation time'),
    sa.Column('imp_prob_norm', sa.Numeric(), nullable=True, comment='Optional normalized probability after removing overround'),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Unstructured payload as captured from the provider'),
    sa.ForeignKeyConstraint(['market_id'], ['market.market_id'], name=op.f('fk_provider_quote_market_id_market'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], name=op.f('fk_provider_quote_provider_id_provider')),
    sa.PrimaryKeyConstraint('quote_id', name=op.f('pk_provider_quote'))
    )
    op.create_index('ix_provider_quote_market_ts', 'provider_quote', ['market_id', 'ts'], unique=False)
    op.create_index('ix_provider_quote_provider_ts', 'provider_quote', ['provider_id', 'ts'], unique=False)
    op.create_index('uq_provider_quote', 'provider_quote', ['provider_id', 'market_id', 'ts', 'side'], unique=True)
    op.create_table('submission_outcome_score',
    sa.Column('submission_id', sa.BigInteger(), nullable=False, comment='Miner submission being evaluated for outcome-calibrated metrics'),
    sa.Column('brier', sa.Numeric(), nullable=True, comment='Miner Brier score for this market'),
    sa.Column('logloss', sa.Numeric(), nullable=True, comment='Miner log loss'),
    sa.Column('provider_brier', sa.Numeric(), nullable=True, comment='Reference provider Brier score'),
    sa.Column('provider_logloss', sa.Numeric(), nullable=True, comment='Reference provider log loss'),
    sa.Column('pss', sa.Numeric(), nullable=True, comment='Predictive skill score (1 - Brier_miner / Brier_provider)'),
    sa.Column('pss_brier', sa.Numeric(), nullable=True, comment='PSS using Brier score'),
    sa.Column('pss_log', sa.Numeric(), nullable=True, comment='PSS using log loss'),
    sa.Column('outcome_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='One-hot outcome vector for audit (e.g., [0,1,0])'),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True, comment='When the underlying outcome settled (UTC)'),
    sa.ForeignKeyConstraint(['submission_id'], ['miner_submission.submission_id'], name=op.f('fk_submission_outcome_score_submission_id_miner_submission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submission_outcome_score'))
    )
    op.create_table('submission_vs_close',
    sa.Column('submission_id', sa.BigInteger(), nullable=False, comment='Links back to the miner submission being scored'),
    sa.Column('provider_basis', sa.String(), nullable=False, comment='Which provider or basket was used to determine the closing reference'),
    sa.Column('close_ts', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of the closing quote (UTC)'),
    sa.Column('close_odds_eu', sa.Numeric(), nullable=False, comment='Closing decimal odds for the same side'),
    sa.Column('close_imp_prob', sa.Numeric(), nullable=False, comment='Closing implied probability (raw)'),
    sa.Column('close_imp_prob_norm', sa.Numeric(), nullable=False, comment='Closing implied probability after overround normalization'),
    sa.Column('clv_odds', sa.Numeric(), nullable=False, comment='Odds-based closing line value ( (O_miner - O_close) / O_close )'),
    sa.Column('clv_prob', sa.Numeric(), nullable=False, comment='Probability-space edge ( (p_close - p_miner) / p_close )'),
    sa.Column('cle', sa.Numeric(), nullable=False, comment='Closed-line efficiency (expected value: O_miner * p_close - 1)'),
    sa.Column('minutes_to_close', sa.Integer(), nullable=False, comment='How many minutes prior to event start the submission arrived'),
    sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the matched snapshot (closest to submission time)'),
    sa.Column('snapshot_prob', sa.Numeric(), nullable=True, comment='Consensus probability from matched snapshot'),
    sa.Column('snapshot_odds', sa.Numeric(), nullable=True, comment='Consensus odds from matched snapshot'),
    sa.Column('snapshot_lag_minutes', sa.Integer(), nullable=True, comment='Minutes between submission and matched snapshot (negative = snapshot before)'),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, comment='When this delta was computed (UTC)'),
    sa.Column('ground_truth_version', sa.Integer(), nullable=True, comment='Version of ground truth (sportsbook bias) used for this computation'),
    sa.ForeignKeyConstraint(['submission_id'], ['miner_submission.submission_id'], name=op.f('fk_submission_vs_close_submission_id_miner_submission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submission_vs_close'))
    )
    op.create_index('ix_submission_vs_close_cle', 'submission_vs_close', ['cle'], unique=False)
    op.create_index('ix_submission_vs_close_clv', 'submission_vs_close', ['clv_prob'], unique=False)
    op.create_index('ix_submission_vs_close_minutes', 'submission_vs_close', ['minutes_to_close'], unique=False)
    op.create_index('ix_submission_vs_close_snapshot', 'submission_vs_close', ['snapshot_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_vs_close_snapshot', table_name='submission_vs_close')
    op.drop_index('ix_submission_vs_close_minutes', table_name='submission_vs_close')
    op.drop_index('ix_submission_vs_close_clv', table_name='submission_vs_close')
    op.drop_index('ix_submission_vs_close_cle', table_name='submission_vs_close')
    op.drop_table('submission_vs_close')
    op.drop_table('submission_outcome_score')
    op.drop_index('uq_provider_quote', table_name='provider_quote')
    op.drop_index('ix_provider_quote_provider_ts', table_name='provider_quote')
    op.drop_index('ix_provider_quote_market_ts', table_name='provider_quote')
    op.drop_table('provider_quote')
    op.drop_table('provider_closing')
    op.drop_table('outcome')
    op.drop_index('uq_miner_submission', table_name='miner_submission')
    op.drop_index('ix_miner_submission_miner_ts', table_name='miner_submission')
    op.drop_index('ix_miner_submission_market_ts', table_name='miner_submission')
    op.drop_table('miner_submission')
    op.drop_index('ix_miner_market_stats_window_end', table_name='miner_market_stats')
    op.drop_table('miner_market_stats')
    op.drop_index('ix_gt_snapshot_market_ts', table_name='ground_truth_snapshot')
    op.drop_index('ix_gt_snapshot_closing', table_name='ground_truth_snapshot')
    op.drop_table('ground_truth_snapshot')
    op.drop_index('ix_ground_truth_closing_computed', table_name='ground_truth_closing')
    op.drop_index('ix_ground_truth_closing_bias_version', table_name='ground_truth_closing')
    op.drop_table('ground_truth_closing')
    op.drop_index('ix_scores_task_type', table_name='scores')
    op.drop_index('ix_scores_score_event', table_name='scores')
    op.drop_index('ix_scores_miner_hotkey', table_name='scores')
    op.drop_index('ix_scores_event_id', table_name='scores')
    op.drop_index('ix_scores_created_at', table_name='scores')
    op.drop_index('ix_scores_component', table_name='scores')
    op.drop_table('scores')
    op.drop_index('uq_market_event_kind_line_team', table_name='market')
    op.drop_index('ix_market_event_kind', table_name='market')
    op.drop_table('market')
    op.drop_index('ix_event_status_start', table_name='event')
    op.drop_index('ix_event_league_start', table_name='event')
    op.drop_table('event')
    op.drop_table('team')
    op.drop_index('ix_sportsbook_bias_version', table_name='sportsbook_bias')
    op.drop_index('ix_sportsbook_bias_computed', table_name='sportsbook_bias')
    op.drop_table('sportsbook_bias')
    op.drop_index('ix_sportsbook_provider', table_name='sportsbook')
    op.drop_index('ix_sportsbook_active', table_name='sportsbook')
    op.drop_table('sportsbook')
    op.drop_index('ix_miner_rolling_score_skill', table_name='miner_rolling_score')
    op.drop_index('ix_miner_rolling_score_as_of', table_name='miner_rolling_score')
    op.drop_table('miner_rolling_score')
    op.drop_table('league')
    op.drop_table('sport')
    op.drop_index('ix_scoring_worker_heartbeat_last', table_name='scoring_worker_heartbeat')
    op.drop_table('scoring_worker_heartbeat')
    op.drop_index('uq_scoring_work_queue_type_chunk', table_name='scoring_work_queue')
    op.drop_index('ix_scoring_work_queue_type_status', table_name='scoring_work_queue')
    op.drop_index('ix_scoring_work_queue_status', table_name='scoring_work_queue')
    op.drop_index('ix_scoring_work_queue_priority', table_name='scoring_work_queue')
    op.drop_index('ix_scoring_work_queue_claimed', table_name='scoring_work_queue')
    op.drop_table('scoring_work_queue')
    op.drop_index('ix_scoring_job_state_status', table_name='scoring_job_state')
    op.drop_index('ix_scoring_job_state_next_run', table_name='scoring_job_state')
    op.drop_table('scoring_job_state')
    op.drop_table('provider')
    op.drop_index('ix_outbox_topic', table_name='outbox')
    op.drop_index('ix_outbox_sent', table_name='outbox')
    op.drop_index('ix_outbox_created_at', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_miner_netuid_uid', table_name='miner')
    op.drop_table('miner')
    op.drop_index('ix_inbox_topic', table_name='inbox')
    op.drop_index('ix_inbox_processed_at', table_name='inbox')
    op.drop_index('ix_inbox_processed', table_name='inbox')
    op.drop_index('ix_inbox_created_at', table_name='inbox')
    op.drop_table('inbox')
    # ### end Alembic commands ###
    bind = op.get_bind()
    _drop_enums(bind)
