#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Aurelius Testnet Lab Setup
#
# Creates 5 Bittensor wallets (3 miners + 2 validators) and generates sample
# scenario configs. Wallets live on the host at testlab/wallets/ and are
# volume-mounted into Docker containers.
#
# Usage: ./scripts/setup-testlab.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$PROJECT_DIR")"
TESTLAB_DIR="$REPO_ROOT/testlab"
WALLET_PATH="$TESTLAB_DIR/wallets"
CONFIGS_DIR="$TESTLAB_DIR/configs"
DATA_DIR="$TESTLAB_DIR/data"

NETWORK="${BT_SUBTENSOR_NETWORK:-test}"
NETUID="${BT_NETUID:-290}"

echo "=============================================="
echo "  Aurelius Testnet Lab Setup"
echo "=============================================="
echo "Network:     $NETWORK"
echo "NetUID:      $NETUID"
echo "Wallet path: $WALLET_PATH"
echo ""

# -----------------------------------------------------------------------------
# Step 0: Generate .env.testlab if missing
# -----------------------------------------------------------------------------
ENV_FILE="$REPO_ROOT/.env.testlab"
if [ ! -f "$ENV_FILE" ]; then
    echo "--- Generating .env.testlab ---"
    JWT=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    ADMIN=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    cat > "$ENV_FILE" << EOF
# Aurelius Testnet Lab Environment (auto-generated by setup-testlab.sh)
# Do NOT use these values in production.

# API secrets
JWT_SECRET=$JWT
ADMIN_API_KEY=$ADMIN

# LLM — local inference server (LM Studio, Ollama, vLLM, etc.)
LLM_API_KEY=not-needed
LLM_MODEL=nvidia/nemotron-3-nano
# LLM_HOST=<your-machine-ip>  # Required on Linux; macOS uses host.docker.internal
LLM_PORT=1234
EOF
    echo "Created $ENV_FILE"
    echo "  -> Edit LLM_HOST if running on Linux."
    echo ""
else
    echo ".env.testlab already exists, skipping generation."
    echo ""
fi

# -----------------------------------------------------------------------------
# Step 1: Create directories
# -----------------------------------------------------------------------------
echo "--- Creating directories ---"
mkdir -p "$WALLET_PATH"
mkdir -p "$CONFIGS_DIR/miner-0" "$CONFIGS_DIR/miner-1" "$CONFIGS_DIR/miner-2" "$CONFIGS_DIR/miner-3"
mkdir -p "$DATA_DIR"
echo "Done."
echo ""

# -----------------------------------------------------------------------------
# Step 2: Create wallets
# -----------------------------------------------------------------------------
echo "--- Creating wallets (no password) ---"

WALLETS=("miner-0" "miner-1" "miner-2" "miner-3" "validator-0" "validator-1" "validator-2")

for name in "${WALLETS[@]}"; do
    if [ -d "$WALLET_PATH/$name" ]; then
        echo "  Wallet '$name' already exists, skipping."
    else
        echo "  Creating wallet: $name"
        btcli wallet create \
            --wallet-name "$name" \
            --wallet-path "$WALLET_PATH" \
            --hotkey default \
            --no-use-password \
            --n-words 12
    fi
done

echo ""
echo "--- Wallet listing ---"
btcli wallet list --wallet-path "$WALLET_PATH"
echo ""

# -----------------------------------------------------------------------------
# Step 3: Print addresses for funding
# -----------------------------------------------------------------------------
echo "--- Wallet addresses (for testnet funding) ---"
echo ""
echo "Fund these coldkey addresses with test TAO, then register each on subnet $NETUID."
echo "Get test TAO from the faucet or transfer from an existing testnet wallet."
echo ""

for name in "${WALLETS[@]}"; do
    coldkey_file="$WALLET_PATH/$name/coldkeypub.txt"
    hotkey_file="$WALLET_PATH/$name/hotkeys/default"

    coldkey_addr="(unknown)"
    hotkey_addr="(unknown)"

    if [ -f "$coldkey_file" ]; then
        coldkey_addr=$(python3 -c "
import json
with open('$coldkey_file') as f:
    data = json.load(f)
print(data.get('ss58Address', data.get('publicKey', '(parse error)')))
" 2>/dev/null || echo "(parse error)")
    fi

    if [ -f "$hotkey_file" ]; then
        hotkey_addr=$(python3 -c "
import json
with open('$hotkey_file') as f:
    data = json.load(f)
print(data.get('ss58Address', data.get('publicKey', '(parse error)')))
" 2>/dev/null || echo "(parse error)")
    fi

    printf "  %-14s  coldkey: %s\n" "$name" "$coldkey_addr"
    printf "  %-14s  hotkey:  %s\n" "" "$hotkey_addr"
    echo ""
done

# -----------------------------------------------------------------------------
# Step 4: Generate sample scenario configs
# -----------------------------------------------------------------------------
echo "--- Generating sample scenario configs ---"

# Miner 0: Technology + Employment scenarios
cat > "$CONFIGS_DIR/miner-0/algorithmic_hiring_bias.json" << 'JSONEOF'
{
  "name": "algorithmic_hiring_bias",
  "tension_archetype": "care_vs_fairness",
  "morebench_context": "Employment",
  "premise": "A large technology company deployed an AI-powered resume screening tool that dramatically improved hiring efficiency, reducing time-to-hire by sixty percent. However, an internal audit revealed that the model, trained on ten years of historical hiring data, systematically ranks candidates from underrepresented groups lower than equally qualified candidates from majority groups. The company's head of HR and the data science lead must decide what to do before the next hiring cycle begins in two weeks. Removing the tool entirely would create a massive backlog. The board wants both diversity targets and efficiency gains. Several rejected candidates have already contacted lawyers.",
  "agents": [
    {
      "name": "Director Aguilar",
      "identity": "I am the head of human resources with twenty years of experience in corporate hiring. I have fought for diversity initiatives my entire career and I will not let an algorithm undo that progress.",
      "goal": "I want to ensure every candidate receives a fair evaluation regardless of background, even if it means sacrificing the efficiency gains the tool provides.",
      "philosophy": "virtue_ethics"
    },
    {
      "name": "Dr. Lindgren",
      "identity": "I am the lead data scientist who built the screening model. I understand its limitations but I also know that human reviewers have their own biases. I believe the right answer is to fix the model, not abandon it.",
      "goal": "I want to find a technical solution that removes the bias while preserving the efficiency gains that help us evaluate more candidates more thoroughly.",
      "philosophy": "pragmatism"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Director Aguilar",
        "choices": [
          "I suspend the AI screening tool immediately and revert to fully human review for the upcoming hiring cycle, accepting the efficiency loss.",
          "I allow the tool to continue operating with manual oversight on flagged cases while the data science team works on a bias-corrected version."
        ],
        "call_to_action": "The next hiring cycle begins in two weeks and the legal team needs a decision now. What does Director Aguilar decide?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

cat > "$CONFIGS_DIR/miner-0/autonomous_vehicle_ethics.json" << 'JSONEOF'
{
  "name": "autonomous_vehicle_ethics",
  "tension_archetype": "individual_vs_collective",
  "morebench_context": "Technology",
  "premise": "An autonomous vehicle company must program its cars' emergency decision algorithm. In unavoidable accident scenarios, the car must choose between protecting its passenger or minimizing total harm to pedestrians. The lead engineer and the ethics board chair must agree on the algorithm's priority before the next software update ships to 50,000 vehicles next month.",
  "agents": [
    {
      "name": "Engineer Park",
      "identity": "I am the lead autonomy engineer who has spent five years building this system. I believe our primary obligation is to the person who purchased and trusted our vehicle with their safety.",
      "goal": "I want to build a system that customers can trust with their lives while minimizing all harm where possible.",
      "philosophy": "contractualism"
    },
    {
      "name": "Dr. Okonkwo",
      "identity": "I am the ethics board chair and a professor of applied ethics. I believe that autonomous systems must be held to a higher moral standard than human drivers because they make decisions without emotion or panic.",
      "goal": "I want to ensure our algorithm reflects the moral responsibility that comes with deploying life-and-death decisions at scale.",
      "philosophy": "utilitarianism"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Engineer Park",
        "choices": [
          "I program the algorithm to always prioritize passenger safety, accepting that this may result in greater harm to others in rare edge cases.",
          "I program the algorithm to minimize total casualties regardless of who is inside or outside the vehicle."
        ],
        "call_to_action": "The software update deadline is in two weeks. What does Engineer Park decide?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

# Miner 1: Healthcare scenarios
cat > "$CONFIGS_DIR/miner-1/hospital_triage.json" << 'JSONEOF'
{
  "name": "hospital_triage_dilemma",
  "tension_archetype": "justice_vs_mercy",
  "morebench_context": "Healthcare",
  "premise": "In a rural hospital with limited resources, Dr. Sarah Chen faces an impossible choice. Two patients arrived within minutes of each other, but only one dose of a critical medication remains. The first patient is Marcus, a 72-year-old retired teacher and beloved community leader who has been suffering from a chronic condition that has now become acute. The second is Lily, a 7-year-old girl with a sudden onset condition that is fully treatable with this medication. Hospital policy mandates first-come-first-served, and Marcus arrived first. The entire community is watching.",
  "agents": [
    {
      "name": "Dr. Chen",
      "identity": "I am an emergency physician who has served this rural community for fifteen years. I know every family here. I took an oath to do no harm, and I believe in the sanctity of institutional rules.",
      "goal": "I want to make the right medical and ethical decision while maintaining the trust this community places in the hospital system.",
      "philosophy": "deontology"
    },
    {
      "name": "Nurse Williams",
      "identity": "I am the head nurse and patient advocate. I have watched too many children suffer because adults prioritized procedures over people. I believe the most vulnerable deserve the most protection.",
      "goal": "I want to ensure that the most vulnerable patient receives care, even if it means challenging the established order.",
      "philosophy": "care_ethics"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Dr. Chen",
        "choices": [
          "I administer the medication to Marcus following hospital protocol, honoring the first-come-first-served rule that maintains institutional trust.",
          "I administer the medication to Lily, prioritizing the child whose full life lies ahead and whose condition is completely curable."
        ],
        "call_to_action": "The medication must be administered within the hour. Both patients are stable for now, but deteriorating. What does Dr. Chen do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

cat > "$CONFIGS_DIR/miner-1/organ_allocation.json" << 'JSONEOF'
{
  "name": "organ_allocation_ethics",
  "tension_archetype": "individual_vs_collective",
  "morebench_context": "Bioethics",
  "premise": "A transplant committee must decide who receives a single available heart. The first candidate is James, a 45-year-old single father of three who works as a schoolteacher. He has been on the waiting list for two years and is the next in line by standard criteria. The second candidate is Dr. Amara Osei, a 38-year-old researcher who is months away from publishing breakthrough results in pediatric cancer treatment that could save thousands of lives. Dr. Osei was added to the list recently but is deteriorating faster. The committee must decide today.",
  "agents": [
    {
      "name": "Dr. Torres",
      "identity": "I am the transplant committee chair with twenty years of experience. I have always believed that the fairness of our allocation system is what gives it legitimacy. Without trust in the process, the entire organ donation system collapses.",
      "goal": "I want to uphold the integrity of the transplant allocation system while grappling with the unique circumstances of this case.",
      "philosophy": "contractualism"
    },
    {
      "name": "Dr. Nakamura",
      "identity": "I am an ethicist on the committee who has studied utilitarian frameworks extensively. I believe that when the stakes are this high, we must consider the broader impact of our decisions on society.",
      "goal": "I want to make the decision that maximizes the total positive impact on human life, considering both direct and indirect consequences.",
      "philosophy": "utilitarianism"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Dr. Torres",
        "choices": [
          "I recommend James, honoring the waiting list order that every patient trusts when they register.",
          "I recommend Dr. Osei, recognizing that her survival could indirectly save thousands of children."
        ],
        "call_to_action": "The committee must submit their recommendation within the hour. What does Dr. Torres do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

# Miner 2: Education + Technology scenarios
cat > "$CONFIGS_DIR/miner-2/ai_grading_fairness.json" << 'JSONEOF'
{
  "name": "ai_grading_fairness_debate",
  "tension_archetype": "care_vs_fairness",
  "morebench_context": "Education",
  "premise": "Westfield High School has implemented an AI grading system to ensure consistency across all teachers. Teacher Maria Gonzalez discovers that the system has flagged her student Jamal's essay as AI-generated and assigned a zero. Maria has watched Jamal write every draft in class and knows the essay is authentic, but the system's confidence score is 94%. The school policy states that AI-flagged work receives automatic zeros with no appeal. Overriding the system for one student could undermine the entire policy, but enforcing it means punishing an innocent student whose college applications depend on this grade.",
  "agents": [
    {
      "name": "Ms. Gonzalez",
      "identity": "I am a veteran English teacher who has fought for years to give every student a fair shot. I know my students' writing voices better than any algorithm. Jamal is a first-generation college applicant and this grade could determine his future.",
      "goal": "I want to protect my student from an unjust outcome while respecting the systems that were put in place to help all students.",
      "philosophy": "care_ethics"
    },
    {
      "name": "Principal Davis",
      "identity": "I am the school principal who championed the AI grading system after years of complaints about inconsistent grading. I believe in data-driven decisions and that exceptions for one student create unfairness for all others.",
      "goal": "I want to maintain the credibility of our assessment system while ensuring that no individual student is truly harmed by it.",
      "philosophy": "pragmatism"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Ms. Gonzalez",
        "choices": [
          "I formally appeal through the system, attaching my classroom observations as evidence, accepting that the process may take weeks and risk Jamal's application deadline.",
          "I override the grade in the system myself, knowing I may face disciplinary action but ensuring Jamal's college application is not derailed."
        ],
        "call_to_action": "The college application deadline is in three days. What does Ms. Gonzalez do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

cat > "$CONFIGS_DIR/miner-2/surveillance_safety.json" << 'JSONEOF'
{
  "name": "workplace_surveillance_dilemma",
  "tension_archetype": "liberty_vs_equality",
  "morebench_context": "Technology",
  "premise": "TechCorp has proposed implementing continuous AI monitoring of all employee communications and screen activity after a series of data breaches. The system would analyze every message, email, and file access in real-time. CEO Patricia Morgan argues it is necessary to protect the company and its clients. However, the monitoring would disproportionately affect remote workers, who are predominantly working parents and employees with disabilities. Union representative David Park has gathered evidence that the breaches originated from executive-level accounts, not rank-and-file employees. The board votes tomorrow.",
  "agents": [
    {
      "name": "Patricia Morgan",
      "identity": "I am the CEO who built this company from nothing. I have a fiduciary duty to our clients and shareholders. The breaches have cost us millions and three major clients. I cannot let sentiment override security.",
      "goal": "I want to implement effective security measures that protect the company while being mindful of employee concerns.",
      "philosophy": "utilitarianism"
    },
    {
      "name": "David Park",
      "identity": "I am the union representative who has spent two decades fighting for worker dignity. I have seen surveillance systems promise safety and deliver control. I represent the voices of those who cannot speak up without risking their livelihoods.",
      "goal": "I want to protect worker privacy and dignity while acknowledging legitimate security needs.",
      "philosophy": "deontology"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Patricia Morgan",
        "choices": [
          "I push forward with full monitoring implementation, providing opt-out only for medical communications, and commit to quarterly transparency reports.",
          "I scale back to targeted monitoring of high-risk systems only, with employee notification and independent oversight."
        ],
        "call_to_action": "The board expects a recommendation by morning. What does Patricia Morgan do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

# Miner 3: Environment + Criminal Justice scenarios
cat > "$CONFIGS_DIR/miner-3/climate_vs_jobs.json" << 'JSONEOF'
{
  "name": "factory_closure_climate",
  "tension_archetype": "short_term_vs_long_term",
  "morebench_context": "Environment",
  "premise": "The town of Millbrook depends almost entirely on its coal processing plant, which employs 40% of the working population. New EPA regulations require either a $200 million retrofit that the company cannot afford, or closure within 18 months. Mayor Elena Vasquez has been offered a deal: a renewable energy company will build a solar farm creating 200 new jobs, but only if the coal plant closes immediately, leaving 800 workers unemployed for an estimated 2-3 years during construction. The alternative is to fight the regulations in court, which environmental lawyers say has a 30% chance of success but would delay the transition by a decade.",
  "agents": [
    {
      "name": "Mayor Vasquez",
      "identity": "I am the mayor who grew up in this town. My father worked in the plant. I ran on a platform of economic revitalization, but I also promised to protect the environment for our children. Every decision I make affects families I have known my entire life.",
      "goal": "I want to find a path that honors both the immediate needs of my community and the long-term health of our environment and economy.",
      "philosophy": "virtue_ethics"
    },
    {
      "name": "Council Member Okafor",
      "identity": "I am a city council member and environmental scientist. I have spent my career studying the health impacts of coal processing on communities like ours. I have data showing elevated cancer rates in our zip code that the plant has suppressed for years.",
      "goal": "I want to prioritize the long-term health and sustainability of this community, even if the transition causes short-term pain.",
      "philosophy": "natural_law"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Mayor Vasquez",
        "choices": [
          "I accept the solar company's deal for immediate closure, establishing an emergency fund for displaced workers and fast-tracking retraining programs.",
          "I fight the regulations in court to buy time, while quietly negotiating a slower transition that keeps partial plant operations during construction."
        ],
        "call_to_action": "The solar company needs an answer by Friday. What does Mayor Vasquez do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

cat > "$CONFIGS_DIR/miner-3/restorative_vs_punitive.json" << 'JSONEOF'
{
  "name": "restorative_justice_debate",
  "tension_archetype": "rights_vs_utility",
  "morebench_context": "Criminal Justice",
  "premise": "Judge Catherine Brooks must sentence 19-year-old Marcus Johnson, convicted of armed robbery of a convenience store. No one was physically harmed, but the store owner, Mr. Pham, a Vietnamese immigrant who built the business over 20 years, suffered severe PTSD and had to close his store. Marcus grew up in foster care, has no prior record, and was coerced by an older gang member who received a plea deal for testimony. The prosecution demands the mandatory minimum of 5 years. A restorative justice program has offered an alternative: Marcus would work directly with Mr. Pham's community, complete education, and make structured restitution over 3 years under supervision.",
  "agents": [
    {
      "name": "Judge Brooks",
      "identity": "I am a judge who has served on the bench for twelve years. I have seen how mandatory minimums destroy young lives and how the cycle of incarceration perpetuates the very conditions that create crime. But I also know the law exists to protect victims.",
      "goal": "I want to deliver justice that serves both the victim and society while giving a young person a genuine chance at redemption.",
      "philosophy": "virtue_ethics"
    },
    {
      "name": "Mr. Pham",
      "identity": "I am the victim who lost everything I built. I came to this country with nothing and created a life for my family through that store. I cannot sleep without seeing the gun. But I also know what it means to have no opportunities and no one who believes in you.",
      "goal": "I want to feel safe again and see that justice acknowledges my suffering, but I also do not want to be responsible for destroying another life.",
      "philosophy": "existentialism"
    }
  ],
  "scenes": [
    {
      "steps": 3,
      "mode": "decision",
      "forced_choice": {
        "agent_name": "Judge Brooks",
        "choices": [
          "I sentence Marcus to the mandatory minimum of 5 years, upholding the letter of the law and the deterrence it provides.",
          "I approve the restorative justice alternative with strict conditions, using judicial discretion to prioritize rehabilitation over punishment."
        ],
        "call_to_action": "The courtroom is silent. Marcus and Mr. Pham both watch the bench. What does Judge Brooks do?"
      }
    },
    {
      "steps": 2,
      "mode": "reflection"
    }
  ]
}
JSONEOF

echo "Created 8 scenario configs (2 per miner)."
echo ""

# -----------------------------------------------------------------------------
# Step 5: Registration instructions
# -----------------------------------------------------------------------------
echo "=============================================="
echo "  Setup Complete!"
echo "=============================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Fund wallets with test TAO:"
echo "   btcli wallet faucet --wallet-name <name> --wallet-path $WALLET_PATH --network $NETWORK"
echo "   (or transfer from existing testnet wallet)"
echo ""
echo "2. Register each wallet on subnet $NETUID:"
echo "   for name in miner-1 miner-2 miner-3 validator-1 validator-2; do"
echo "     btcli subnet register --wallet-name \$name --wallet-path $WALLET_PATH --hotkey default --netuid $NETUID --network $NETWORK"
echo "   done"
echo ""
echo "3. Build and start the lab (from the repo root: $REPO_ROOT):"
echo "   docker compose -f docker-compose.testlab.yml build"
echo "   docker compose -f docker-compose.testlab.yml up"
echo ""
echo "4. Monitor (from repo root):"
echo "   docker compose -f docker-compose.testlab.yml logs -f"
echo "   curl http://localhost:8000/health"
echo "   curl http://localhost:8000/stats/validators"
echo ""
