FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

ENV PROJECT_ROOT=/app

# Install git (required for the version script)
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --frozen --no-install-project

# Copy the entire project (including .git and get_version.py)
COPY . .

# Run the script with uv to generate version.txt (now .git is available)
RUN uv run python get_version.py

# Copy version.txt to the app directory (from /tmp/version.txt generated by the script)
RUN cp /tmp/version.txt /app/version.txt

# Expose port
EXPOSE 8000

#CMD ["uv", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uv", "run", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
