"""init schema

Revision ID: 02c17f499ccf
Revises:
Create Date: 2025-08-04 09:52:25.446660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02c17f499ccf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_id"), "categories", ["id"], unique=False
    )
    op.create_table(
        "dynamic_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "metagraph_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("coldkey", sa.String(), nullable=False),
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column("alpha_stake", sa.Float(), nullable=False),
        sa.Column("tao_stake", sa.Float(), nullable=False),
        sa.Column("stake", sa.Float(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("ip_type", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("validator_version", sa.String(), nullable=True),
        sa.Column("is_enough_weight", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metagraph_nodes_id"), "metagraph_nodes", ["id"], unique=False
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("miner_hotkey", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base_url"),
    )
    op.create_index(op.f("ix_sites_id"), "sites", ["id"], unique=False)
    op.create_table(
        "validator_sync_offset",
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column(
            "last_coupon_action_date",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_sync_time", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("hotkey"),
    )
    op.create_table(
        "coupons",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("used_on_product_url", sa.String(), nullable=True),
        sa.Column("restrictions", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("discount_value", sa.String(), nullable=True),
        sa.Column("discount_percentage", sa.Integer(), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("source_hotkey", sa.String(), nullable=False),
        sa.Column("miner_hotkey", sa.String(), nullable=False),
        sa.Column("last_action", sa.Integer(), nullable=False),
        sa.Column("last_action_date", sa.Integer(), nullable=False),
        sa.Column("last_action_signature", sa.String(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_checked_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("code", "site_id", "miner_hotkey"),
    )
    # ### end Alembic commands ###
    op.create_table(
        "coupon_action_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("miner_hotkey", sa.String(), nullable=False),
        sa.Column("action", sa.Integer(), nullable=False),
        sa.Column("action_date", sa.Integer(), nullable=False),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("source_hotkey", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["code", "site_id", "miner_hotkey"],
            ["coupons.code", "coupons.site_id", "coupons.miner_hotkey"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coupon_action_logs_id"),
        "coupon_action_logs",
        ["id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coupons_id"), table_name="coupons")
    op.drop_table("coupons")
    op.drop_table("validator_sync_offset")
    op.drop_index(op.f("ix_sites_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_metagraph_nodes_id"), table_name="metagraph_nodes")
    op.drop_table("metagraph_nodes")
    op.drop_table("dynamic_config")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
