"""add rule to coupon

Revision ID: 9f3895518c21
Revises: cb22074ea0d8
Create Date: 2025-09-05 11:28:07.106148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f3895518c21"
down_revision: Union[str, Sequence[str], None] = "cb22074ea0d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coupons", sa.Column("rule", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coupons", "rule")
    # ### end Alembic commands ###
