"""api url for site

Revision ID: cb22074ea0d8
Revises: 033cda3d191b
Create Date: 2025-09-04 11:28:21.943687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb22074ea0d8"
down_revision: Union[str, Sequence[str], None] = "033cda3d191b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("api_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "api_url")
    # ### end Alembic commands ###
