"""add coupon ownership table

Revision ID: e1b2c3d4a5f6
Revises: 9f3895518c21
Create Date: 2025-10-13 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1b2c3d4a5f6"
down_revision: Union[str, Sequence[str], None] = "9f3895518c21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon_ownerships",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("owner_hotkey", sa.String(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_contested_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("contest_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("code", "site_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coupon_ownerships")
    # ### end Alembic commands ###
