"""add debt_balance

Revision ID: b94328315877
Revises: 4928d551a7c2
Create Date: 2026-03-11 12:37:15.547887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94328315877'
down_revision: Union[str, Sequence[str], None] = '4928d551a7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_wins', sa.Column('debt_balance', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_wins', 'debt_balance')
    # ### end Alembic commands ###
