"""init

Revision ID: 4928d551a7c2
Revises: 
Create Date: 2026-03-09 20:38:54.815971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4928d551a7c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('auction_id', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('vault_owner', sa.String(), nullable=True),
    sa.Column('vault_id', sa.Integer(), nullable=True),
    sa.Column('bidder', sa.String(), nullable=True),
    sa.Column('bid_id', sa.BigInteger(), nullable=True),
    sa.Column('bid_amount', sa.BigInteger(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('winning_bid', sa.BigInteger(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auction_events_auction_id', 'auction_events', ['auction_id'], unique=False)
    op.create_index('ix_auction_events_block_number', 'auction_events', ['block_number'], unique=False)
    op.create_index('ix_auction_events_event_type', 'auction_events', ['event_type'], unique=False)
    op.create_table('auction_wins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_hotkey', sa.String(), nullable=False),
    sa.Column('winning_bid', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tempo_block', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id')
    )
    op.create_index('ix_auction_wins_block_number', 'auction_wins', ['block_number'], unique=False)
    op.create_index('ix_auction_wins_tempo_block', 'auction_wins', ['tempo_block'], unique=False)
    op.create_index('ix_auction_wins_winner_hotkey', 'auction_wins', ['winner_hotkey'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auction_wins_winner_hotkey', table_name='auction_wins')
    op.drop_index('ix_auction_wins_tempo_block', table_name='auction_wins')
    op.drop_index('ix_auction_wins_block_number', table_name='auction_wins')
    op.drop_table('auction_wins')
    op.drop_index('ix_auction_events_event_type', table_name='auction_events')
    op.drop_index('ix_auction_events_block_number', table_name='auction_events')
    op.drop_index('ix_auction_events_auction_id', table_name='auction_events')
    op.drop_table('auction_events')
    # ### end Alembic commands ###
