"""add_external_id_to_event

Revision ID: 4c8d2b4a52a9
Revises: 0002_create_event_market_tables
Create Date: 2026-01-07 19:10:32.197101
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8d2b4a52a9'
down_revision = '0002_create_event_market_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_event_external_id'), 'event', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_external_id'), table_name='event')
    op.drop_column('event', 'external_id')
    # ### end Alembic commands ###

