"""Tests for v1747 outcome_signer.

Loads the JSON fixture generated by scripts/v1747_golden_vectors.py and verifies
the validator-side computation is byte-identical with both Python (the script)
and Solidity (Foundry tests in contracts/test/LineOutcomeRegistry.t.sol).

If any of these tests fail, the schema is broken: validators and the contract
will disagree on lineHashes, signatures will fail to recover, and the protocol
won't reach consensus.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from djinn_validator.chain.outcome_signer import (
    EIP712_DOMAIN_NAME,
    EIP712_DOMAIN_VERSION,
    LineKey,
    eip712_digest,
    eip712_domain_separator,
    line_hash,
    outcome_ruleset_hash,
    sign_line_outcome,
    signer_from_signature,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE = REPO_ROOT / "contracts" / "test" / "fixtures" / "v1747_golden_vectors.json"


@pytest.fixture(scope="module")
def fixture():
    with open(FIXTURE) as f:
        return json.load(f)


def test_outcome_ruleset_hash_matches_fixture(fixture):
    expected = fixture["env"]["outcome_ruleset_hash"]
    actual = "0x" + outcome_ruleset_hash().hex()
    assert actual == expected, f"OUTCOME_RULESET_HASH drift: {actual} vs {expected}"


def test_domain_constants_match_fixture(fixture):
    assert fixture["env"]["domain_name"] == EIP712_DOMAIN_NAME
    assert fixture["env"]["domain_version"] == EIP712_DOMAIN_VERSION


def test_domain_separator_matches_fixture(fixture):
    chain_id = fixture["env"]["chain_id"]
    addr = fixture["env"]["registry_address"]
    expected = fixture["env"]["domain_separator"]
    actual = "0x" + eip712_domain_separator(chain_id, addr).hex()
    assert actual == expected, f"domain separator drift: {actual} vs {expected}"


@pytest.mark.parametrize("vector_idx", range(12))
def test_line_hash_matches_fixture(fixture, vector_idx):
    """Every golden vector's lineHash must match what outcome_signer produces."""
    v = fixture["vectors"][vector_idx]
    chain_id = fixture["env"]["chain_id"]
    addr = fixture["env"]["registry_address"]

    key = LineKey(
        sport=v["sport"],
        event_id=v["event_id"],
        market=v["market"],
        side=v["side"],
        line_value=v["line_value"],
    )
    assert key.canonical_string() == v["canonical_string"], \
        f"canonical_string drift on {v['name']}"

    actual = "0x" + line_hash(key, chain_id, addr).hex()
    assert actual == v["line_hash"], \
        f"lineHash drift on {v['name']}: {actual} vs {v['line_hash']}"


@pytest.mark.parametrize("vector_idx", range(12))
def test_eip712_digest_matches_fixture(fixture, vector_idx):
    v = fixture["vectors"][vector_idx]
    chain_id = fixture["env"]["chain_id"]
    addr = fixture["env"]["registry_address"]
    line_hash_bytes = bytes.fromhex(v["line_hash"][2:])

    actual = "0x" + eip712_digest(line_hash_bytes, v["outcome"], chain_id, addr).hex()
    assert actual == v["digest"], \
        f"digest drift on {v['name']}: {actual} vs {v['digest']}"


@pytest.mark.parametrize("vector_idx", range(12))
def test_signature_recovers_to_signer(fixture, vector_idx):
    """Verify each fixture's signature recovers to the expected signer EOA."""
    v = fixture["vectors"][vector_idx]
    chain_id = fixture["env"]["chain_id"]
    addr = fixture["env"]["registry_address"]
    line_hash_bytes = bytes.fromhex(v["line_hash"][2:])
    sig_bytes = bytes.fromhex(v["signature"][2:])

    recovered = signer_from_signature(sig_bytes, line_hash_bytes, v["outcome"], chain_id, addr)
    assert recovered.lower() == v["signer"].lower(), \
        f"signer mismatch on {v['name']}: recovered {recovered} vs expected {v['signer']}"


def test_sign_then_verify_round_trip(fixture):
    """Signing with our test key + recovering with our function == fixture signer."""
    v = fixture["vectors"][0]
    chain_id = fixture["env"]["chain_id"]
    addr = fixture["env"]["registry_address"]
    privkey = fixture["env"]["test_signer_keys"][0]
    expected_signer = fixture["env"]["test_signer_addresses"][0]
    line_hash_bytes = bytes.fromhex(v["line_hash"][2:])

    sig = sign_line_outcome(privkey, line_hash_bytes, v["outcome"], chain_id, addr)
    assert len(sig) == 65, f"sig must be 65 bytes, got {len(sig)}"

    recovered = signer_from_signature(sig, line_hash_bytes, v["outcome"], chain_id, addr)
    assert recovered.lower() == expected_signer.lower()
    # Should also match the fixture's pinned signature byte-for-byte
    assert "0x" + sig.hex() == v["signature"], "deterministic signature drift"


def test_pending_outcome_rejected():
    """Validators must never sign Pending (=0)."""
    with pytest.raises(ValueError):
        sign_line_outcome(
            "0x" + "0" * 63 + "1",
            bytes(32),
            0,  # Pending
            84532,
            "0x" + "0" * 40,
        )


def test_invalid_outcome_rejected():
    with pytest.raises(ValueError):
        sign_line_outcome(
            "0x" + "0" * 63 + "1",
            bytes(32),
            42,  # Out of range
            84532,
            "0x" + "0" * 40,
        )


def test_canonical_string_moneyline_trailing_pipe():
    """Moneyline produces a canonical string with a trailing pipe (empty line_value)."""
    key = LineKey("basketball_nba", "401584293", "moneyline", "home", "")
    assert key.canonical_string().endswith("|")
    assert key.canonical_string() == "DJINN_LINE_V1|basketball_nba|401584293|moneyline|home|"


def test_canonical_string_no_internal_whitespace():
    """No accidental whitespace in canonical strings."""
    key = LineKey("basketball_nba", "401584293", "spread", "home", "-3.5")
    s = key.canonical_string()
    assert " " not in s
    assert "\t" not in s
    assert "\n" not in s
