"""Executor price_per_gpu

Revision ID: 33be5b1944a8
Revises: 20ad305cfb00
Create Date: 2025-11-06 18:17:09.230004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '33be5b1944a8'
down_revision: Union[str, None] = '20ad305cfb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor', sa.Column('price_per_gpu', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executor', 'price_per_gpu')
    # ### end Alembic commands ###
