"""add docker_port and index on rented_for_pod_id

Revision ID: 5a2cd580f6ca
Revises: ba52e4725227
Create Date: 2025-11-14 19:34:59.255112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a2cd580f6ca'
down_revision: Union[str, None] = 'ba52e4725227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portmapping', sa.Column('rented_for_pod_id', sa.Uuid(), nullable=True))
    op.add_column('portmapping', sa.Column('docker_port', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_portmapping_rented_for_pod_id'), 'portmapping', ['rented_for_pod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portmapping_rented_for_pod_id'), table_name='portmapping')
    op.drop_column('portmapping', 'docker_port')
    op.drop_column('portmapping', 'rented_for_pod_id')
    # ### end Alembic commands ###
