default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check --fix --force-exclude
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        types: [python]
        require_serial: true

      - id: pytest
        name: pytest
        entry: uv run pytest tests/ -x -q
        language: system
        pass_filenames: false
        stages: [pre-push]
