from core.const import REQUIRED_DEPOSIT_AMOUNT

NEW_GPU_MODELS = {
    "NVIDIA GeForce GTX 1060",
    "NVIDIA GeForce GTX 1070",
    "NVIDIA GeForce GTX 1070 Ti",
    "NVIDIA GeForce GTX 1080",
    "NVIDIA GeForce GTX 1080 Ti",
    "NVIDIA GeForce GTX 1660",
    "NVIDIA GeForce GTX 1660 SUPER",
    "NVIDIA GeForce GTX 1660 Ti",
    "NVIDIA GeForce RTX 2060",
    "NVIDIA GeForce RTX 2060 SUPER",
    "NVIDIA GeForce RTX 2070 SUPER",
    "NVIDIA GeForce RTX 2080 SUPER",
    "NVIDIA GeForce RTX 2080 Ti",
    "NVIDIA GeForce RTX 3050",
    "NVIDIA GeForce RTX 3060",
    "NVIDIA GeForce RTX 3060 Laptop GPU",
    "NVIDIA GeForce RTX 3060 Ti",
    "NVIDIA GeForce RTX 3070",
    "NVIDIA GeForce RTX 3070 Ti",
    "NVIDIA GeForce RTX 3080",
    "NVIDIA GeForce RTX 3080 Ti",
    "NVIDIA GeForce RTX 3090 Ti",
    "NVIDIA GeForce RTX 4060",
    "NVIDIA GeForce RTX 4060 Ti",
    "NVIDIA GeForce RTX 4070",
    "NVIDIA GeForce RTX 4070 SUPER",
    "NVIDIA GeForce RTX 4070 Ti",
    "NVIDIA GeForce RTX 4070 Ti SUPER",
    "NVIDIA GeForce RTX 4080",
    "NVIDIA GeForce RTX 4080 SUPER",
    "NVIDIA GeForce RTX 5060",
    "NVIDIA GeForce RTX 5060 Ti",
    "NVIDIA GeForce RTX 5070",
    "NVIDIA GeForce RTX 5070 Ti",
    "NVIDIA GeForce RTX 5080",
    "NVIDIA A10 Tensor Core GPU",
    "NVIDIA Quadro P4000",
    "NVIDIA Quadro RTX 5000",
    "NVIDIA Quadro RTX 6000",
    "NVIDIA Quadro RTX 8000",
    "NVIDIA RTX A2000",
    "NVIDIA T4 Tensor Core GPU",
    "NVIDIA Tesla V100 Tensor Core GPU",
    "NVIDIA Tesla M40",
    "NVIDIA Tesla P100",
    "NVIDIA Tesla P40",
    "NVIDIA TITAN RTX",
    "NVIDIA TITAN V",
    "NVIDIA TITAN Xp",
    "NVIDIA RTX 5000 Ada Generation",
    "NVIDIA RTX 5880 Ada Generation",
    "NVIDIA RTX PRO 4000 Blackwell",
    "NVIDIA RTX PRO 5000 Blackwell",
}


def test_new_gpu_models_have_deposit_constants():
    for model in NEW_GPU_MODELS:
        assert model in REQUIRED_DEPOSIT_AMOUNT
        assert REQUIRED_DEPOSIT_AMOUNT[model] > 0
