"""init_db_schema

Revision ID: 9eb3205c2a56
Revises:
Create Date: 2025-04-27 11:15:52.146133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9eb3205c2a56"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("node_hotkey", sa.String(), nullable=False),
        sa.Column("node_netuid", sa.Integer(), nullable=False),
        sa.Column("_record_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_record_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("node_hotkey", "node_netuid"),
        sa.UniqueConstraint(
            "node_hotkey", "node_netuid", name="uq_node_hotkey_node_netuid"
        ),
    )
    op.create_table(
        "social_accounts",
        sa.Column(
            "platform_type",
            sa.Enum("TWITTER", name="platform_type_enum"),
            nullable=False,
        ),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("account_username", sa.String(), nullable=True),
        sa.Column("node_hotkey", sa.String(), nullable=True),
        sa.Column("node_netuid", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column("_record_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_record_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_hotkey", "node_netuid"],
            ["nodes.node_hotkey", "nodes.node_netuid"],
        ),
        sa.PrimaryKeyConstraint("platform_type", "account_id"),
        sa.UniqueConstraint(
            "platform_type", "account_id", name="uq_platform_type_account_id"
        ),
    )
    op.create_table(
        "posts",
        sa.Column(
            "platform_type",
            sa.Enum("TWITTER", name="platform_type_enum"),
            nullable=False,
        ),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "NEW", "ACCEPTED", "REJECTED", "ERROR", name="processing_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("processing_note", sa.Text(), nullable=True),
        sa.Column("_record_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_record_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_type", "account_id"],
            ["social_accounts.platform_type", "social_accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("platform_type", "post_id"),
        sa.UniqueConstraint(
            "platform_type", "post_id", name="uq_platform_type_post_id"
        ),
    )
    op.create_table(
        "interactions",
        sa.Column(
            "platform_type",
            sa.Enum("TWITTER", name="platform_type_enum"),
            nullable=False,
        ),
        sa.Column("interaction_id", sa.String(), nullable=False),
        sa.Column(
            "interaction_type",
            sa.Enum("REPLY", name="interaction_type_enum"),
            nullable=False,
        ),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "NEW", "ACCEPTED", "REJECTED", "ERROR", name="processing_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("processing_note", sa.Text(), nullable=True),
        sa.Column("_record_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("_record_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_type", "account_id"],
            ["social_accounts.platform_type", "social_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_type", "post_id"],
            ["posts.platform_type", "posts.post_id"],
        ),
        sa.PrimaryKeyConstraint("platform_type", "interaction_id"),
        sa.UniqueConstraint(
            "platform_type", "interaction_id", name="uq_platform_type_interaction_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interactions")
    op.drop_table("posts")
    op.drop_table("social_accounts")
    op.drop_table("nodes")
    # ### end Alembic commands ###
