# validator hyperparameters (DO NOT EDIT THIS FILE - it will affect scoring)

from pydantic_settings import BaseSettings

class Hyperparameters(BaseSettings):
    """Validator hyperparameters (empty until defined)."""
    pass