"""add_review_keywords_sentiment_columns

Revision ID: 1a2d022d5112
Revises: 85868a1f8465
Create Date: 2025-06-29 19:16:12.129739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2d022d5112'
down_revision: Union[str, None] = '85868a1f8465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner_predictions', sa.Column('review', sa.Text(), nullable=True))
    op.add_column('miner_predictions', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('miner_predictions', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('miner_predictions', sa.Column('keyword_verification_score', sa.Float(), nullable=True))
    op.add_column('miner_predictions', sa.Column('coherence_score', sa.Float(), nullable=True))
    op.add_column('miner_predictions', sa.Column('total_reward', sa.Float(), nullable=True))
    op.add_column('miner_predictions', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('miner_predictions', sa.Column('updated_at', sa.String(), nullable=True))
    # Note: SQLite doesn't support ALTER COLUMN, so we'll keep prediction as INTEGER for now
    # The application will handle the conversion between int and float
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner_predictions', 'updated_at')
    op.drop_column('miner_predictions', 'created_at')
    op.drop_column('miner_predictions', 'total_reward')
    op.drop_column('miner_predictions', 'coherence_score')
    op.drop_column('miner_predictions', 'keyword_verification_score')
    op.drop_column('miner_predictions', 'sentiment')
    op.drop_column('miner_predictions', 'keywords')
    op.drop_column('miner_predictions', 'review')
    # ### end Alembic commands ###
