"""Initial migration

Revision ID: 85868a1f8465
Revises: 
Create Date: 2025-04-23 16:33:25.550016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85868a1f8465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('check_chain_review_done', sa.Boolean(), nullable=True),
    sa.Column('mining_done', sa.Boolean(), nullable=True),
    sa.Column('rewards_distributed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('miner_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('miner_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products._id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'miner_id', name='uix_product_miner')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miner_predictions')
    op.drop_table('products')
    # ### end Alembic commands ###
