"""blacklist_malicious_miners

Revision ID: e315e513306c
Revises: 1a2d022d5112
Create Date: 2025-08-14 22:00:41.346109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e315e513306c"
down_revision: Union[str, None] = "1a2d022d5112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_miners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("miner_id", sa.Integer(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("coldkey", sa.String(), nullable=False),
        sa.Column("blacklist_count", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hotkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blacklisted_miners")
    # ### end Alembic commands ###
