"""
Burn percentage calculator based on sales-to-emissions ratio.

This module calculates the percentage of emissions to burn based on the relationship
between total miner sales and total emissions value, ensuring miners don't become
over-profitable when emissions exceed the value they generate.

⸻
The Core Issue
⸻

Miners might generate something like £10,000 in sales, but emissions paying them in
TAO may be worth £30,000. When emissions are higher than the value miners actually
bring in, miners get over-profitable and naturally sell the extra TAO → USDC, which
increases sell pressure and hurts the subnet's TAO price.

The chain already supports burning a portion of emissions by sending that share of
weights to the subnet-creator hotkey. Those emissions are burned automatically.

⸻
How We Automate the Burn Amount
⸻

To make this work without manual updates, we calculate a percentage to burn every
X hours/days based on the following steps:

1. Get total emission for the period (in TAO)
2. Multiply by TAO/USD to get emission_in_usd
3. Sum the actual sales miners generated → total_sales_usd
4. Get the target sales-to-emission ratio (sales_emission_ratio) from external API
   - 1.0 = 1:1 ratio (miners earn what they generate)
   - 1.5 = 1.5:1 ratio (miners can earn up to 1.5× their sales)
   - 2.0 = 2:1 ratio (more generous, but more burn needed if sales fall behind)
5. Calculate burn percentage:
   - If emissions <= sales * ratio: burn = 0%
   - Otherwise: burn = (emissions - sales * ratio) / emissions * 100%

Examples:
  • Example 1 — No burn needed:
    - Emission: £10,000
    - Miner sales: £10,000
    - Ratio goal: 1:1
    - burn_percentage = (10,000 - 10,000) / 10,000 = 0%
  
  • Example 2 — Need to burn part of emissions:
    - Emission: £15,000
    - Sales: £10,000
    - Ratio goal: 1:1
    - burn_percentage = (15,000 - 10,000) / 15,000 ≈ 33%

⸻
Integration
⸻

The burn percentage is calculated automatically in the validator's burn_percentage_resolver,
which is called during weight setting. The resolver:
1. Fetches burn calculation data (emission_in_tao, tao_price_usd, total_sales_usd, sales_emission_ratio)
2. Calls get_burn_percentage_from_sales() to calculate the burn percentage
3. Returns the percentage to be applied via apply_creator_burn() in the score sink

The subnet recalculates this value every X period, finds the creator's UID, applies that
percentage of weights to the creator hotkey, and those emissions get burned automatically.
No validator updates or manual configuration required.
"""
from typing import Optional


def calculate_burn_percentage(
    emission_in_usd: float,
    total_sales_usd: float,
    target_sales_emission_ratio: float = 1.0,
) -> float:
    """
    Calculate burn percentage based on sales-to-emissions ratio.
    
    The burn percentage ensures that miners don't become over-profitable when
    emissions exceed the value they generate. When emissions are higher than
    the value miners bring in, excess emissions are burned to maintain the
    target profitability ratio.
    
    Formula:
        If target_ratio = 1.0 (1:1 ratio):
            burn_percentage = (emission_in_usd - total_sales_usd) / emission_in_usd * 100
        
        For other ratios (e.g., 1.5:1):
            burn_percentage = (emission_in_usd - total_sales_usd * target_ratio) / emission_in_usd * 100
        
        Result is clamped to [0.0, 100.0]
    
    Args:
        emission_in_usd: Total emission value for the period in USD
        total_sales_usd: Total sales generated by miners in USD
        target_sales_emission_ratio: Target ratio of sales to emissions (default 1.0 for 1:1)
            - 1.0 = miners earn what they generate (1:1)
            - 1.5 = miners can earn up to 1.5× their sales (1.5:1)
            - 2.0 = more generous rewards (2:1)
    
    Returns:
        Burn percentage in [0.0, 100.0]
    
    Examples:
        >>> # Example 1: No burn needed (emissions ≈ sales at 1:1 ratio)
        >>> calculate_burn_percentage(10000, 10000, 1.0)
        0.0
        
        >>> # Example 2: Need to burn part of emissions
        >>> calculate_burn_percentage(15000, 10000, 1.0)
        33.333333333333336
        
        >>> # Example 3: With 1.5:1 ratio (more generous)
        >>> calculate_burn_percentage(15000, 10000, 1.5)
        0.0  # No burn needed since 15000 <= 10000 * 1.5
        
        >>> # Example 4: With 1.5:1 ratio, emissions too high
        >>> calculate_burn_percentage(20000, 10000, 1.5)
        25.0  # Burn 25% since 20000 > 10000 * 1.5
    """
    if emission_in_usd <= 0:
        return 0.0
    
    # Calculate expected emission based on sales and target ratio
    expected_emission = total_sales_usd * target_sales_emission_ratio
    
    # If emissions are less than or equal to expected, no burn needed
    if emission_in_usd <= expected_emission:
        return 0.0
    
    # Calculate burn percentage: (excess emissions) / (total emissions) * 100
    excess_emission = emission_in_usd - expected_emission
    burn_percentage = (excess_emission / emission_in_usd) * 100.0
    
    # Clamp to [0.0, 100.0]
    return max(0.0, min(100.0, burn_percentage))


def calculate_emission_in_usd(
    emission_in_tao: float,
    tao_price_usd: float,
) -> float:
    """
    Calculate emission value in USD from TAO amount.
    
    This is a pure calculation function that multiplies emission amount by price.
    The TAO price should be fetched externally (e.g., via ValidatorBurnDataSource._fetch_tao_price_usd())
    and passed as a parameter.
    
    Args:
        emission_in_tao: Total emission amount in TAO
        tao_price_usd: TAO price in USD (fetched from external source)
    
    Returns:
        Emission value in USD
    
    Example:
        >>> calculate_emission_in_usd(100.0, 500.0)
        50000.0
    """
    return emission_in_tao * tao_price_usd


def get_burn_percentage_from_sales(
    emission_in_tao: float,
    tao_price_usd: float,
    total_sales_usd: float,
    sales_emission_ratio: float,
) -> Optional[float]:
    """
    Calculate burn percentage from sales data and emissions.
    
    This is the main function that combines emission calculation and burn percentage
    calculation. It should be called periodically (e.g., every X hours/days) to
    automatically adjust the burn percentage based on current sales and emissions.
    
    Args:
        emission_in_tao: Total emission amount in TAO for the period
        tao_price_usd: TAO price in USD (should be fetched from external API)
        total_sales_usd: Total sales generated by miners in USD (from sales_emission_ratio API)
        sales_emission_ratio: Target ratio of sales to emissions (from external API)
            - 1.0 = 1:1 ratio (miners earn what they generate)
            - 1.5 = 1.5:1 ratio (miners can earn up to 1.5× their sales)
            - 2.0 = 2:1 ratio (more generous)
    
    Returns:
        Burn percentage in [0.0, 100.0], or None if calculation fails
    
    Example:
        >>> # Emissions worth $15,000, sales $10,000, target 1:1 ratio
        >>> get_burn_percentage_from_sales(30.0, 500.0, 10000.0, 1.0)
        33.333333333333336  # ~33% burn needed
    """
    try:
        # Calculate emission value in USD
        emission_in_usd = calculate_emission_in_usd(emission_in_tao, tao_price_usd)
        
        # Calculate burn percentage
        burn_percentage = calculate_burn_percentage(
            emission_in_usd=emission_in_usd,
            total_sales_usd=total_sales_usd,
            target_sales_emission_ratio=sales_emission_ratio,
        )
        
        return burn_percentage
    except (ValueError, ZeroDivisionError, TypeError) as e:
        # Log error and return None to disable burn
        return None

