"""Minecraft mechanism package."""

from level114.validator.mechanisms.minecraft.constants import (
    BONUS_PLUGINS,
    DEBUG_SCORING,
    DEFAULT_SCORE,
    EMA_ALPHA,
    EXCELLENT_SCORE_THRESHOLD,
    GOOD_SCORE_THRESHOLD,
    IDEAL_TPS,
    MAX_PLAYERS_WEIGHT,
    MAX_RECOVERY_TIME_MINUTES,
    MAX_REPORT_HISTORY,
    MAX_SCORE,
    MAX_SCORE_CHANGE,
    MAX_TPS_BONUS,
    MAX_TPS_COEFFICIENT_OF_VARIATION,
    MIN_PLAYERS_FOR_BONUS,
    MIN_REPORTS_FOR_RELIABILITY,
    MIN_SCORE,
    MIN_SCORE_CHANGE,
    MIN_TPS_THRESHOLD,
    OPTIMAL_PLAYER_RATIO_MAX,
    OPTIMAL_PLAYER_RATIO_MIN,
    POOR_SCORE_THRESHOLD,
    RECOVERY_SAMPLE_COUNT,
    RECOVERY_TPS_THRESHOLD,
    REQUIRED_PLUGINS,
    TPS_STABILITY_WINDOW,
    W_INFRA,
    W_INFRA_TPS,
    W_PART,
    W_PART_COMPLIANCE,
    W_PART_PLAYERS,
    W_RELY,
    W_RELY_PLAYER_POWER,
    W_RELY_RECOVERY,
    W_RELY_STABILITY,
    get_constants_summary,
    get_score_classification,
    validate_constants,
)
from level114.validator.mechanisms.minecraft.mechanism import MinecraftMechanism
from level114.validator.mechanisms.minecraft.scorer import (
    MinerContext,
    apply_score_smoothing,
    calculate_miner_score,
    evaluate_infrastructure,
    evaluate_participation,
    evaluate_reliability,
    normalize_score,
)
from level114.validator.mechanisms.minecraft.scoring import score_server
from level114.validator.mechanisms.minecraft.types import ScoreCacheEntry

__all__ = [
    # Mechanism
    "MinecraftMechanism",
    "ScoreCacheEntry",
    "score_server",
    # Scoring APIs
    "MinerContext",
    "calculate_miner_score",
    "apply_score_smoothing",
    "evaluate_infrastructure",
    "evaluate_participation",
    "evaluate_reliability",
    "normalize_score",
    # Constants helpers
    "validate_constants",
    "get_score_classification",
    "get_constants_summary",
    "IDEAL_TPS",
    "MIN_TPS_THRESHOLD",
    "MAX_TPS_BONUS",
    "MAX_PLAYERS_WEIGHT",
    "MIN_PLAYERS_FOR_BONUS",
    "OPTIMAL_PLAYER_RATIO_MIN",
    "OPTIMAL_PLAYER_RATIO_MAX",
    "REQUIRED_PLUGINS",
    "BONUS_PLUGINS",
    "W_INFRA",
    "W_PART",
    "W_RELY",
    "W_INFRA_TPS",
    "W_PART_COMPLIANCE",
    "W_PART_PLAYERS",
    "W_RELY_PLAYER_POWER",
    "W_RELY_STABILITY",
    "W_RELY_RECOVERY",
    "MIN_SCORE",
    "MAX_SCORE",
    "DEFAULT_SCORE",
    "EMA_ALPHA",
    "MIN_SCORE_CHANGE",
    "MAX_SCORE_CHANGE",
    "EXCELLENT_SCORE_THRESHOLD",
    "GOOD_SCORE_THRESHOLD",
    "POOR_SCORE_THRESHOLD",
    "MAX_REPORT_HISTORY",
    "MIN_REPORTS_FOR_RELIABILITY",
    "TPS_STABILITY_WINDOW",
    "MAX_TPS_COEFFICIENT_OF_VARIATION",
    "RECOVERY_TPS_THRESHOLD",
    "RECOVERY_SAMPLE_COUNT",
    "MAX_RECOVERY_TIME_MINUTES",
    "DEBUG_SCORING",
]
