"""add_blacklist_miner_table

Revision ID: bbc21b4cd363
Revises: daf364e5115a
Create Date: 2025-10-20 21:45:23.530446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbc21b4cd363"
down_revision: Union[str, Sequence[str], None] = "daf364e5115a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklisted_miners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("miner_id", sa.Integer(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("coldkey", sa.String(), nullable=False),
        sa.Column("blacklist_count", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hotkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blacklisted_miners")
    # ### end Alembic commands ###
