name: "CD: Deploying Executor (dev) with Manual Trigger"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: "dev" 
      VALIDATOR_HOTKEY_SS58: "5DHgdomxxHSQf7neJWcagvGhTMKpqvKWwuprEaFF8C653qty"
      TARGET_FILE: "docker-compose.app.dev.yml"
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }} 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x neurons/executor/docker_build.sh
          chmod +x neurons/executor/docker_publish.sh
          chmod +x neurons/executor/docker_runner_build.sh
          chmod +x neurons/executor/docker_runner_publish.sh

      - name: Build and publish executor image
        run: |
          cd neurons/executor
          source ./docker_build.sh
          source ./docker_publish.sh
          echo "EXECUTOR_IMAGE_SHA256=${EXECUTOR_IMAGE_SHA256}" >> $GITHUB_ENV

      - name: Build and publish runner image
        run: |
          cd neurons/executor
          source ./docker_runner_build.sh
          source ./docker_runner_publish.sh
