#!/bin/bash
set -e

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "${BLUE}${BOLD}[STEP]${NC}  $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_OVERRIDE="$SCRIPT_DIR/src/config_override.py"

# ── Cleanup trap ──────────────────────────────────────────────────────────────
cleanup() {
    if [ -f "$CONFIG_OVERRIDE" ]; then
        rm -f "$CONFIG_OVERRIDE"
        log_info "Cleaned up config_override.py"
    fi
}
trap cleanup EXIT

# ── Deploy environment ────────────────────────────────────────────────────────
log_step "Resolving deploy environment..."

if [ -z "$DEPLOY_ENV" ]; then
    log_warn "DEPLOY_ENV is not set."
    read -rp "  Enter deploy environment (local/staging/prod): " DEPLOY_ENV
fi

case "$DEPLOY_ENV" in
    local|staging|prod) ;;
    *)
        log_error "Invalid DEPLOY_ENV: '$DEPLOY_ENV'. Must be one of: local, staging, prod."
        exit 1
        ;;
esac

log_info "Deploy environment: ${BOLD}$DEPLOY_ENV${NC}"

if [ "$DEPLOY_ENV" = "prod" ]; then
    IMAGE_TAG="latest"
else
    IMAGE_TAG="$DEPLOY_ENV"
fi

# ── Required env vars & config_override.py (non-prod only) ────────────────────
if [ "$DEPLOY_ENV" != "prod" ]; then
    log_step "Resolving required configuration..."

    if [ -z "$WATCHTOWER_ENDPOINT_URL" ]; then
        log_warn "WATCHTOWER_ENDPOINT_URL is not set."
        read -rp "  Enter WATCHTOWER_ENDPOINT_URL: " WATCHTOWER_ENDPOINT_URL
    fi

    if [ -z "$WATCHTOWER_ENDPOINT_URL" ]; then
        log_error "WATCHTOWER_ENDPOINT_URL cannot be empty."
        exit 1
    fi

    if [ -z "$WATCHTOWER_VALIDATOR_HOTKEY" ]; then
        log_warn "WATCHTOWER_VALIDATOR_HOTKEY is not set."
        read -rp "  Enter WATCHTOWER_VALIDATOR_HOTKEY: " WATCHTOWER_VALIDATOR_HOTKEY
    fi

    if [ -z "$WATCHTOWER_VALIDATOR_HOTKEY" ]; then
        log_error "WATCHTOWER_VALIDATOR_HOTKEY cannot be empty."
        exit 1
    fi

    log_info "WATCHTOWER_ENDPOINT_URL:    $WATCHTOWER_ENDPOINT_URL"
    log_info "WATCHTOWER_VALIDATOR_HOTKEY: $WATCHTOWER_VALIDATOR_HOTKEY"

    log_step "Generating src/config_override.py..."

    cat > "$CONFIG_OVERRIDE" <<EOF
# Auto-generated by docker_build.sh — DO NOT COMMIT
WATCHTOWER_ENDPOINT_URL = "$WATCHTOWER_ENDPOINT_URL"
WATCHTOWER_VALIDATOR_HOTKEY = "$WATCHTOWER_VALIDATOR_HOTKEY"
EOF

    log_info "config_override.py written to $CONFIG_OVERRIDE"
else
    log_info "Skipping config_override.py for prod (configuration supplied at runtime)."
fi

# ── Docker build ──────────────────────────────────────────────────────────────
IMAGE_NAME="daturaai/lium-watchtower:$IMAGE_TAG"

log_step "Building Docker image: ${BOLD}$IMAGE_NAME${NC}"
docker build -t "$IMAGE_NAME" "$SCRIPT_DIR"

log_info "Build complete: ${BOLD}$IMAGE_NAME${NC}"
