nav:
  - README.md
  - Active Challenges:
      - historical_fingerprinter: ./historical_fingerprinter
      - flowradar vpn detection: ./flowradar
  - Inactive Challenges:
      - dev_fingerprinter: ./dev_fingerprinter
      - ada_detection: ./ada_detection
      - humanize_behaviour: ./humanize_behaviour
      - ab_sniffer: ./ab_sniffer
