
# base event class, handles metadata etc for any event type
import time
import json
import hashlib
import uuid
from typing import Any, Dict, Optional


class Event:
    def __init__(self, event_id: Optional[str], event_type: str, event_data: Dict[str, Any], *, created_at: Optional[float] = None):
        # If no id provided, fallback to random UUID (non-deterministic). Deterministic IDs should
        # be generated by subclasses using make_id() based on natural keys.
        self.event_id = event_id or str(uuid.uuid4())
        self.event_type = event_type
        self.event_data = event_data
        self.created_at = float(created_at) if created_at is not None else time.time()

    @property
    def task_name(self) -> str:
        # Default task route equals event_type; callers may override per subclass
        return self.event_type

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_id": self.event_id,
            "event_type": self.event_type,
            "event_data": self.event_data,
            "created_at": self.created_at,
        }

    def to_task(self) -> Dict[str, Any]:
        """
        Future Celery-compatible payload structure.
        - task: route name
        - args/kwargs: serialized event
        """
        return {
            "task": self.task_name,
            "args": [],
            "kwargs": self.to_dict(),
        }

    @staticmethod
    def canonical_json(value: Any) -> str:
        """
        Canonical JSON for hashing/idempotency: sorted keys, no whitespace, best-effort str fallback.
        """
        return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, default=str)

    @staticmethod
    def make_id(*parts: str, truncate: Optional[int] = 32) -> str:
        """
        Deterministic hex id by hashing provided string parts. Truncate to 128 bits by default.
        """
        base = "||".join(parts).encode("utf-8")
        digest = hashlib.sha256(base).hexdigest()
        return digest[:truncate] if truncate else digest

    @staticmethod
    def bucket_minute(ts_seconds: int | float) -> str:
        try:
            return str(int(float(ts_seconds)) // 60)
        except Exception:
            return "0"