#!/usr/bin/env bash
# refresh-uid-routing.sh -- sync nginx hostname -> IP map from the local
# validator's metagraph view. Cron every minute.
#
# The wildcard *.djinn.gg vhost uses $validator_upstream from this map
# to dynamically route v<uid>.djinn.gg -> the IP that UID currently
# reports to the metagraph. Validators that come and go are picked up
# automatically; the operator never touches DNS or nginx config.
set -euo pipefail

MAP_FILE=/etc/nginx/conf.d/uid-routing-map.conf
NEW_MAP=$(mktemp)

RESP=$(curl -s --max-time 10 http://127.0.0.1:8421/v1/network/validators 2>/dev/null) || {
  rm -f "$NEW_MAP"
  exit 0
}
if [ -z "$RESP" ]; then
  rm -f "$NEW_MAP"
  exit 0
fi

{
  echo "# Auto-generated by refresh-uid-routing.sh -- do not edit by hand"
  echo "# Generated at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "map \$host \$validator_upstream {"
  echo "    default \"\";"
} > "$NEW_MAP"

echo "$RESP" | python3 -c '
import json, sys, ipaddress
try:
    d = json.load(sys.stdin)
    for v in d.get("validators", []):
        uid = v.get("uid")
        ip = v.get("ip", "")
        port = v.get("port", 0)
        if uid is None or not ip or ip == "0.0.0.0" or port == 0:
            continue
        # SECURITY: refuse to route to RFC1918, loopback, or
        # link-local addresses. A malicious validator operator could
        # publish 127.0.0.1 or 192.168.x.x to the metagraph and the
        # router would otherwise proxy to internal services on the
        # router box itself. Public IPs only.
        try:
            addr = ipaddress.ip_address(ip)
            if (addr.is_private or addr.is_loopback or addr.is_link_local
                    or addr.is_multicast or addr.is_reserved
                    or addr.is_unspecified):
                sys.stderr.write(f"skipping uid={uid} non-public ip={ip}\n")
                continue
        except ValueError:
            sys.stderr.write(f"skipping uid={uid} invalid ip={ip}\n")
            continue
        if port < 1 or port > 65535:
            sys.stderr.write(f"skipping uid={uid} bad port={port}\n")
            continue
        print(f"    v{uid}.djinn.gg \"{ip}:{port}\";")
except Exception as e:
    sys.stderr.write(f"parse error: {e}\n")
    sys.exit(0)
' >> "$NEW_MAP"

echo "}" >> "$NEW_MAP"

if ! cmp -s "$NEW_MAP" "$MAP_FILE" 2>/dev/null; then
  mv "$NEW_MAP" "$MAP_FILE"
  if nginx -t 2>/dev/null; then
    systemctl reload nginx 2>/dev/null
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) refresh-uid-routing reloaded nginx"
  else
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) refresh-uid-routing nginx -t FAILED, not reloading" >&2
  fi
else
  rm -f "$NEW_MAP"
fi
