#!/usr/bin/env bash
# staging-e2e.sh
#
# End-to-end orchestrator for P1-06 staging:
#   1. Ensure a Base mainnet fork is up (via scripts/staging-up.sh)
#   2. Fund the deployer with test USDC via whale impersonation
#   3. Deploy Deploy.s.sol against the fork and capture fresh proxy addresses
#   4. Run Playwright on-chain-health journey pointed at the fork with those
#      addresses so we exercise the exact mainnet code path before launch
#
# Exit codes:
#   0 - full pipeline passed, quorum invariants hold on a fresh fork deploy
#   1 - prereq missing / setup failure
#   2 - deploy failed
#   3 - address-parse failed
#   4 - playwright journey failed
#
# Usage:
#   ./scripts/staging-e2e.sh                       # uses public mainnet RPC
#   BASE_MAINNET_RPC=<alchemy-url> ./scripts/staging-e2e.sh
#
#   # Keep the fork alive after the run (skip teardown):
#   STAGING_KEEP=1 ./scripts/staging-e2e.sh
#
# Weekly cron (install on the ops box):
#   0 3 * * 1 cd /home/user/djinn && ./scripts/staging-e2e.sh \
#       > /tmp/staging-e2e-weekly.log 2>&1 \
#       || ( . /home/user/telegram-bot/.env && \
#            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
#              -d "chat_id=${TELEGRAM_CHAT_ID}" \
#              --data-urlencode \
#              "text=staging-e2e weekly dry-run FAILED $(date -u). See /tmp/staging-e2e-weekly.log" )
#
# This script is designed to be cron-safe: deterministic address parsing from
# the Deploy.s.sol _logSummary() section, clean teardown on trap EXIT so a
# hung cron job doesn't leave an anvil zombie, and a single 'set -e' mean
# exit code mirrors the step that failed (see exit-code table above).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

STAGING_UP="$SCRIPT_DIR/staging-up.sh"
RPC_URL="http://localhost:${STAGING_PORT:-8545}"
DEPLOY_LOG="$PROJECT_ROOT/.staging-deploy.log"
ADDR_ENV="$PROJECT_ROOT/.staging-addresses.env"

# Default upstream to the public Base mainnet endpoint so a fresh cron box
# doesn't need any env setup to do the dry run. Operators with an Alchemy or
# Infura key set BASE_MAINNET_RPC explicitly.
export BASE_MAINNET_RPC="${BASE_MAINNET_RPC:-https://mainnet.base.org}"

cleanup() {
  if [ "${STAGING_KEEP:-0}" != "1" ]; then
    echo ""
    echo "=== Tearing down fork ==="
    "$STAGING_UP" down || true
  else
    echo ""
    echo "STAGING_KEEP=1 — leaving fork at $RPC_URL running."
    echo "Run '$STAGING_UP down' to stop it."
  fi
}
trap cleanup EXIT

echo "=== Staging E2E · $(date -u) ==="
echo "Upstream:  $BASE_MAINNET_RPC"
echo "Fork:      $RPC_URL"
echo ""

echo "--- [1/4] Ensuring fork is up ---"
"$STAGING_UP" up

echo ""
echo "--- [2/4] Funding deployer with test USDC ---"
"$STAGING_UP" fund

echo ""
echo "--- [3/4] Deploying contracts to fork ---"
# Capture the stdout so we can parse the _logSummary section. We tee so the
# operator (and cron logs) can still see the broadcast output in real time.
if ! "$STAGING_UP" deploy 2>&1 | tee "$DEPLOY_LOG"; then
  echo "ERROR: staging-up.sh deploy failed; see $DEPLOY_LOG" >&2
  exit 2
fi

# _logSummary emits lines of the form '  KEY= 0xADDRESS' — forge prefixes
# each script log line with two spaces. console.log inserts a single space
# between arguments, so the regex allows leading whitespace and a space after
# the '='. We extract into the ON_CHAIN_HEALTH_* env var names the spec
# expects. `|| true` keeps set -e from tripping when grep finds no match; the
# caller validates emptiness explicitly in the `required` loop below.
extract_addr() {
  local key="$1"
  grep -Eo "^\s*${key}=\s+0x[0-9a-fA-F]{40}" "$DEPLOY_LOG" 2>/dev/null \
    | tail -1 \
    | awk '{print $2}' \
    || true
}

TIMELOCK=$(extract_addr "TIMELOCK_ADDRESS")
SC=$(extract_addr "NEXT_PUBLIC_SIGNAL_COMMITMENT_ADDRESS")
ESC=$(extract_addr "NEXT_PUBLIC_ESCROW_ADDRESS")
COLL=$(extract_addr "NEXT_PUBLIC_COLLATERAL_ADDRESS")
ACCT=$(extract_addr "NEXT_PUBLIC_ACCOUNT_ADDRESS")
AUD=$(extract_addr "NEXT_PUBLIC_AUDIT_ADDRESS")
CL=$(extract_addr "NEXT_PUBLIC_CREDIT_LEDGER_ADDRESS")
OV=$(extract_addr "OUTCOME_VOTING_ADDRESS")
USDC=$(extract_addr "NEXT_PUBLIC_USDC_ADDRESS")

required=(TIMELOCK SC ESC COLL ACCT AUD CL OV USDC)
for var in "${required[@]}"; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: failed to parse $var from $DEPLOY_LOG" >&2
    exit 3
  fi
done

# Persist for operator inspection + sourcing
cat > "$ADDR_ENV" <<EOF
# Generated by scripts/staging-e2e.sh · $(date -u)
# Fresh addresses from a Base-mainnet-fork deploy. NOT for production use.
ON_CHAIN_HEALTH_RPC=$RPC_URL
ON_CHAIN_HEALTH_TIMELOCK=$TIMELOCK
ON_CHAIN_HEALTH_SIGNAL_COMMITMENT=$SC
ON_CHAIN_HEALTH_ESCROW=$ESC
ON_CHAIN_HEALTH_COLLATERAL=$COLL
ON_CHAIN_HEALTH_ACCOUNT=$ACCT
ON_CHAIN_HEALTH_AUDIT=$AUD
ON_CHAIN_HEALTH_CREDIT_LEDGER=$CL
ON_CHAIN_HEALTH_OUTCOME_VOTING=$OV
STAGING_USDC=$USDC
EOF
echo ""
echo "Parsed fresh addresses → $ADDR_ENV"
echo "  TIMELOCK_ADDRESS=$TIMELOCK"
echo "  USDC=$USDC"

echo ""
echo "--- [4/4] Running Playwright on-chain-health journey against fork ---"
cd "$PROJECT_ROOT/web"
set -a
. "$ADDR_ENV"
set +a

# The on-chain-health spec doesn't touch the UI, so we can run it directly with
# the ux config; baseURL is irrelevant for these two tests. We scope to
# on-chain-health.spec.ts so we only rerun what this staging run actually
# validates.
if ! xvfb-run -a npx playwright test e2e/ux/journeys/on-chain-health.spec.ts \
     --config playwright.ux.config.ts 2>&1; then
  echo "ERROR: on-chain-health spec FAILED against fork" >&2
  exit 4
fi

echo ""
echo "=== PASS · staging-e2e complete ==="
