# Generated by Django 4.2.23 on 2025-07-11 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weightsbatch",
            options={"verbose_name_plural": "Weights Batches"},
        ),
    ]
