# Generated by Django 4.2.23 on 2025-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0004_remove_delivered_from_auctionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsbatch",
            name="mechanism_id",
            field=models.IntegerField(default=0, help_text="Mechanism ID (0=legacy, 1=auctions)"),
        ),
        migrations.AlterField(
            model_name="auctionresult",
            name="winners",
            field=models.JSONField(default=list, help_text="Selected bids with delivery flag"),
        ),
        migrations.AlterField(
            model_name="weightsbatch",
            name="block",
            field=models.BigIntegerField(help_text="Block number for which this batch is scheduled"),
        ),
        migrations.AlterUniqueTogether(
            name="weightsbatch",
            unique_together={("block", "mechanism_id")},
        ),
    ]
