# Generated by Django 4.2.23 on 2025-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0005_add_mechanism_id_to_weights_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="LuxorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this snapshot was taken by the scraper",
                    ),
                ),
                (
                    "subaccount_name",
                    models.CharField(help_text="Luxor subaccount name", max_length=255),
                ),
                (
                    "worker_name",
                    models.CharField(
                        help_text="Worker identifier (e.g., hotkey_worker1)",
                        max_length=255,
                    ),
                ),
                ("hashrate", models.BigIntegerField(help_text="Hashrate in H/s")),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Efficiency percentage",
                        max_digits=10,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=10, help_text="Revenue in BTC", max_digits=20),
                ),
                (
                    "last_updated",
                    models.DateTimeField(help_text="Timestamp when Luxor last updated this data"),
                ),
            ],
            options={
                "ordering": ["-snapshot_time"],
                "indexes": [
                    models.Index(
                        fields=["subaccount_name", "worker_name", "snapshot_time"],
                        name="validator_l_subacco_94ab7a_idx",
                    ),
                    models.Index(
                        fields=["snapshot_time", "worker_name"],
                        name="validator_l_snapsho_afff09_idx",
                    ),
                ],
            },
        ),
    ]
