# Generated by Django 4.2.23 on 2025-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0006_luxorsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedMiner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotkey",
                    models.CharField(
                        db_index=True,
                        help_text="Miner hotkey that is banned",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "banned_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the ban was applied or last updated (for repeat offenses)",
                    ),
                ),
                (
                    "epoch_start",
                    models.BigIntegerField(help_text="Epoch start block where underdelivery was detected"),
                ),
                (
                    "window_number",
                    models.IntegerField(help_text="Window number (0-5) where underdelivery occurred"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason for ban (e.g., 'underdelivered 90%')",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "ordering": ["-banned_at"],
                "indexes": [
                    models.Index(
                        fields=["hotkey", "banned_at"],
                        name="validator_b_hotkey_3dbc92_idx",
                    ),
                    models.Index(
                        fields=["epoch_start", "window_number"],
                        name="validator_b_epoch_s_20f7cc_idx",
                    ),
                ],
            },
        ),
    ]
