# Generated by Django 4.2.23 on 2025-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0007_bannedminer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=32)),
                ("observed_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("price_fp18", models.DecimalField(decimal_places=0, max_digits=40)),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["metric", "observed_at"],
                        name="validator_p_metric_ed4f71_idx",
                    ),
                    models.Index(
                        fields=["metric", "source", "observed_at"],
                        name="validator_p_metric_e2240c_idx",
                    ),
                ],
            },
        ),
    ]
