# Generated by Django 4.2.23 on 2025-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0008_priceobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionresult",
            name="alpha_tao_fp18",
            field=models.BigIntegerField(
                blank=True,
                help_text="ALPHA/TAO price consensus in FP18 format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="hashp_usdc_fp18",
            field=models.BigIntegerField(
                blank=True,
                help_text="Hashrate price consensus (USDC per PH per day) in FP18 format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="tao_usdc_fp18",
            field=models.BigIntegerField(
                blank=True,
                help_text="TAO/USDC price consensus in FP18 format",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auctionresult",
            name="winners",
            field=models.JSONField(
                default=list,
                help_text="Delivered winners with hashrate and price multiplier",
            ),
        ),
    ]
