# Generated by Django 4.2.23 on 2025-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0009_auctionresult_alpha_tao_fp18_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionresult",
            name="alpha_tao_fp18",
        ),
        migrations.RemoveField(
            model_name="auctionresult",
            name="hashp_usdc_fp18",
        ),
        migrations.RemoveField(
            model_name="auctionresult",
            name="tao_usdc_fp18",
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="alpha_tao",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="ALPHA/TAO price consensus",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="hashp_usdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="Hashrate price consensus (USDC per PH per day)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="tao_usdc",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                help_text="TAO/USDC price consensus",
                max_digits=30,
                null=True,
            ),
        ),
    ]
