# Generated by Django 4.2.23 on 2025-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0010_remove_auctionresult_alpha_tao_fp18_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatorScrapingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the scraping occurred",
                    ),
                ),
                (
                    "block_number",
                    models.BigIntegerField(db_index=True, help_text="Block number when scraping occurred"),
                ),
                (
                    "worker_count",
                    models.IntegerField(default=0, help_text="Number of workers scraped in this event"),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(fields=["block_number"], name="validator_v_block_n_601221_idx"),
                    models.Index(fields=["scraped_at"], name="validator_v_scraped_a31680_idx"),
                ],
            },
        ),
    ]
