# Generated by Django 4.2.23 on 2025-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0011_validatorscrapingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionresult",
            name="skipped_delivery_check",
            field=models.BooleanField(
                default=False,
                help_text="True when delivery validation was skipped due to scraping gaps",
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="underdelivered_hotkeys",
            field=models.JSONField(
                default=list,
                help_text="Unique hotkeys that failed delivery checks during this window",
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="banned_hotkeys",
            field=models.JSONField(
                default=list,
                help_text="Hotkeys banned from this window after ban consensus",
            ),
        ),
    ]
