# Generated by Django 4.2.23 on 2025-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0012_auctionresult_delivery_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionresult",
            name="commitments_ph_by_hotkey",
            field=models.JSONField(
                default=dict,
                help_text="Total committed hashrate per hotkey (PH) for this window",
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="wins_ph_by_hotkey",
            field=models.JSONField(
                default=dict,
                help_text="Total winning hashrate per hotkey (PH) for this window",
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="total_budget_ph",
            field=models.DecimalField(
                max_digits=30,
                decimal_places=6,
                null=True,
                blank=True,
                help_text="Estimated auction budget for this window in PH",
            ),
        ),
    ]
