# Generated by Django 4.2.23 on 2026-01-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0013_auctionresult_budget_and_sums"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionresult",
            name="start_ts",
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Timestamp of the window start block",
            ),
        ),
        migrations.AddField(
            model_name="auctionresult",
            name="end_ts",
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Timestamp of the window end block",
            ),
        ),
    ]
